"""Curated demo dataset for the fictional supermarket ``MercaEjemplo``.

Pure data only — no I/O and no ORM. The seed script (:mod:`cestaplan_api.scripts.seed_demo`)
consumes these tables to build a synthetic catalogue and recipe book. Everything here is
FICTIONAL and must always be stored with ``is_synthetic=True`` / ``source_type='demo'``.

Design invariants that keep the catalogue internally consistent:

- Every recipe ingredient references a ``canonical_name`` that exists in :data:`INGREDIENTS`.
  Each ingredient yields catalogue products with a price, so every recipe is satisfiable.
- Recipe ingredient units always equal the ingredient's ``default_unit`` and every product of
  that ingredient is sold in the same base unit, so the ingredient->product conversion factor
  is exactly ``1`` and the deterministic engine can resolve quantities without ambiguity.
- Nutrition figures are per 100 g (or per 100 ml for liquids); the seed writes them verbatim
  as the ``basis_quantity=100`` nutrition row.
"""

from __future__ import annotations

from typing import Final, TypedDict

# ---------------------------------------------------------------------------
# Fictional retailer / store / source identity
# ---------------------------------------------------------------------------

RETAILER_SLUG: Final = "mercaejemplo"
RETAILER_NAME: Final = "MercaEjemplo"
STORE_EXTERNAL_CODE: Final = "ME-001"
STORE_NAME: Final = "MercaEjemplo Centro"
STORE_PROVINCE: Final = "Madrid"
STORE_LOCALITY: Final = "Madrid"
STORE_POSTAL_CODE: Final = "28013"
# A SECOND fictional store of the same chain, priced ~15% cheaper on the identical
# catalogue so choosing store A vs B yields a different total cost/coverage. This makes
# switching stores in the wizard meaningful. Both stores price every product, so both
# catalogues stay fully satisfiable for planning.
STORE2_EXTERNAL_CODE: Final = "ME-002"
STORE2_NAME: Final = "MercaEjemplo Norte"
STORE2_PROVINCE: Final = "Madrid"
STORE2_LOCALITY: Final = "Alcobendas"
STORE2_POSTAL_CODE: Final = "28100"
STORE2_PRICE_FACTOR: Final = "0.85"
DATA_SOURCE_SLUG: Final = "demo-mercaejemplo"
DATA_SOURCE_NAME: Final = "MercaEjemplo (supermercado demo ficticio)"
SOURCE_NAME: Final = "MercaEjemplo demo"

# Fictional, clearly-fake brands used to build product variants.
BRANDS: Final = ("MarcaDemo", "MercaEjemplo Selección", "EcoDemo")

# ---------------------------------------------------------------------------
# 12 product categories (ProductCategory-equivalent groupings). In the vertical
# slice ``Product`` has no category column, so the grouping is carried by
# ``Ingredient.category_code``; these are the 12 canonical codes.
# ---------------------------------------------------------------------------

CATEGORIES: Final[list[tuple[str, str]]] = [
    ("verduras", "Verduras y hortalizas"),
    ("frutas", "Frutas"),
    ("carne", "Carnes"),
    ("pescado_marisco", "Pescados y mariscos"),
    ("lacteos", "Lácteos"),
    ("huevos", "Huevos"),
    ("cereales_pasta_arroz", "Cereales, pasta y arroz"),
    ("legumbres", "Legumbres"),
    ("panaderia", "Panadería"),
    ("aceites_condimentos", "Aceites y condimentos"),
    ("frutos_secos_semillas", "Frutos secos y semillas"),
    ("conservas_despensa", "Conservas y despensa"),
]


class IngredientSpec(TypedDict):
    """One canonical ingredient plus the package sizes it is sold in."""

    name: str
    display: str
    cat: str
    unit: str  # base unit: g | ml | unit
    density: float | None  # g per ml (liquids), else None
    allergens: list[str]
    traces: list[str]
    # per-100(g|ml): kcal, protein, carb, sugars, fat, sat_fat, fiber, salt
    nutr: tuple[float, float, float, float, float, float, float, float]
    # each package (quantity in base unit, pack price EUR) -> one catalogue product
    packages: list[tuple[float, str]]


def _ing(
    name: str,
    display: str,
    cat: str,
    unit: str,
    allergens: list[str],
    nutr: tuple[float, float, float, float, float, float, float, float],
    packages: list[tuple[float, str]],
    *,
    density: float | None = None,
    traces: list[str] | None = None,
) -> IngredientSpec:
    return {
        "name": name,
        "display": display,
        "cat": cat,
        "unit": unit,
        "density": density,
        "allergens": allergens,
        "traces": traces or [],
        "nutr": nutr,
        "packages": packages,
    }


# 75 canonical ingredients x 2 packages each = 150 catalogue products.
INGREDIENTS: Final[list[IngredientSpec]] = [
    # --- verduras (8) ---
    _ing(
        "tomate",
        "Tomate",
        "verduras",
        "g",
        [],
        (18, 0.9, 3.9, 2.6, 0.2, 0, 1.2, 0.01),
        [(1000, "5.20"), (500, "1.15")],
    ),
    _ing(
        "cebolla",
        "Cebolla",
        "verduras",
        "g",
        [],
        (40, 1.1, 9.3, 4.2, 0.1, 0, 1.7, 0.01),
        [(1000, "1.19"), (2000, "2.15")],
    ),
    _ing(
        "ajo",
        "Ajo",
        "verduras",
        "g",
        [],
        (149, 6.4, 33, 1, 0.5, 0.1, 2.1, 0.02),
        [(150, "1.05"), (250, "1.60")],
    ),
    _ing(
        "pimiento_rojo",
        "Pimiento rojo",
        "verduras",
        "g",
        [],
        (31, 1, 6, 4.2, 0.3, 0, 2.1, 0.01),
        [(500, "1.95"), (750, "2.70")],
    ),
    _ing(
        "calabacin",
        "Calabacín",
        "verduras",
        "g",
        [],
        (17, 1.2, 3.1, 2.5, 0.3, 0.1, 1, 0.01),
        [(500, "1.10"), (1000, "1.99")],
    ),
    _ing(
        "zanahoria",
        "Zanahoria",
        "verduras",
        "g",
        [],
        (41, 0.9, 9.6, 4.7, 0.2, 0, 2.8, 0.07),
        [(1000, "1.09"), (500, "0.69")],
    ),
    _ing(
        "espinaca",
        "Espinaca",
        "verduras",
        "g",
        [],
        (23, 2.9, 3.6, 0.4, 0.4, 0.1, 2.2, 0.08),
        [(250, "1.49"), (500, "2.60")],
    ),
    _ing(
        "patata",
        "Patata",
        "verduras",
        "g",
        [],
        (77, 2, 17, 0.8, 0.1, 0, 2.2, 0.01),
        [(2000, "1.89"), (5000, "3.99")],
    ),
    # --- frutas (7) ---
    _ing(
        "manzana",
        "Manzana",
        "frutas",
        "g",
        [],
        (52, 0.3, 14, 10, 0.2, 0, 2.4, 0),
        [(1000, "1.99"), (500, "1.10")],
    ),
    _ing(
        "platano",
        "Plátano",
        "frutas",
        "g",
        [],
        (89, 1.1, 23, 12, 0.3, 0.1, 2.6, 0),
        [(1000, "1.55"), (750, "1.25")],
    ),
    _ing(
        "naranja",
        "Naranja",
        "frutas",
        "g",
        [],
        (47, 0.9, 12, 9, 0.1, 0, 2.4, 0),
        [(2000, "2.49"), (1000, "1.39")],
    ),
    _ing(
        "fresa",
        "Fresa",
        "frutas",
        "g",
        [],
        (32, 0.7, 7.7, 4.9, 0.3, 0, 2, 0),
        [(500, "2.29"), (250, "1.30")],
    ),
    _ing(
        "limon",
        "Limón",
        "frutas",
        "g",
        [],
        (29, 1.1, 9.3, 2.5, 0.3, 0, 2.8, 0),
        [(500, "1.15"), (1000, "1.99")],
    ),
    _ing(
        "aguacate",
        "Aguacate",
        "frutas",
        "g",
        [],
        (160, 2, 9, 0.7, 15, 2.1, 7, 0),
        [(400, "2.60"), (200, "1.45")],
    ),
    _ing(
        "arandano",
        "Arándano",
        "frutas",
        "g",
        [],
        (57, 0.7, 14, 10, 0.3, 0, 2.4, 0),
        [(125, "1.95"), (250, "3.60")],
    ),
    # --- carne (7) ---
    _ing(
        "pollo_pechuga",
        "Pechuga de pollo",
        "carne",
        "g",
        [],
        (165, 31, 0, 0, 3.6, 1, 0, 0.1),
        [(500, "3.49"), (1000, "6.60")],
    ),
    _ing(
        "pollo_muslo",
        "Muslo de pollo",
        "carne",
        "g",
        [],
        (209, 26, 0, 0, 11, 3, 0, 0.1),
        [(1000, "4.20"), (500, "2.35")],
    ),
    _ing(
        "ternera_picada",
        "Ternera picada",
        "carne",
        "g",
        [],
        (250, 26, 0, 0, 15, 6, 0, 0.1),
        [(500, "4.95"), (1000, "9.40")],
    ),
    _ing(
        "cerdo_lomo",
        "Lomo de cerdo",
        "carne",
        "g",
        [],
        (242, 27, 0, 0, 14, 5, 0, 0.1),
        [(600, "4.10"), (300, "2.25")],
    ),
    _ing(
        "pavo_pechuga",
        "Pechuga de pavo",
        "carne",
        "g",
        [],
        (135, 29, 0, 0, 1, 0.3, 0, 0.1),
        [(500, "3.95"), (1000, "7.60")],
    ),
    _ing(
        "chorizo",
        "Chorizo",
        "carne",
        "g",
        ["sulphite"],
        (455, 24, 1.9, 0.5, 38, 14, 0, 2.8),
        [(200, "2.30"), (400, "4.30")],
    ),
    _ing(
        "jamon_cocido",
        "Jamón cocido",
        "carne",
        "g",
        [],
        (145, 18, 1.5, 1, 7.5, 2.5, 0, 2.2),
        [(200, "2.10"), (400, "3.95")],
    ),
    # --- pescado_marisco (6) ---
    _ing(
        "salmon",
        "Salmón",
        "pescado_marisco",
        "g",
        ["fish"],
        (208, 20, 0, 0, 13, 3, 0, 0.1),
        [(400, "6.20"), (250, "4.10")],
    ),
    _ing(
        "merluza",
        "Merluza",
        "pescado_marisco",
        "g",
        ["fish"],
        (72, 17, 0, 0, 0.9, 0.2, 0, 0.1),
        [(500, "5.40"), (300, "3.45")],
    ),
    _ing(
        "atun_lata",
        "Atún en lata",
        "pescado_marisco",
        "g",
        ["fish"],
        (116, 26, 0, 0, 1, 0.3, 0, 0.4),
        [(300, "3.20"), (150, "1.75")],
    ),
    _ing(
        "gambas",
        "Gambas",
        "pescado_marisco",
        "g",
        ["crustacean"],
        (99, 24, 0.2, 0, 0.3, 0.1, 0, 0.6),
        [(400, "5.95"), (200, "3.20")],
    ),
    _ing(
        "bacalao",
        "Bacalao",
        "pescado_marisco",
        "g",
        ["fish"],
        (82, 18, 0, 0, 0.7, 0.1, 0, 0.2),
        [(400, "6.80"), (250, "4.40")],
    ),
    _ing(
        "mejillones",
        "Mejillones",
        "pescado_marisco",
        "g",
        ["mollusc"],
        (86, 12, 3.7, 0, 2.2, 0.4, 0, 0.3),
        [(1000, "3.40"), (500, "1.95")],
    ),
    # --- lacteos (7) ---
    _ing(
        "leche_entera",
        "Leche entera",
        "lacteos",
        "ml",
        ["milk"],
        (61, 3.2, 4.8, 4.8, 3.3, 2, 0, 0.1),
        [(1000, "0.89"), (1500, "1.29")],
        density=1.03,
    ),
    _ing(
        "leche_desnatada",
        "Leche desnatada",
        "lacteos",
        "ml",
        ["milk"],
        (34, 3.4, 5, 5, 0.1, 0.1, 0, 0.1),
        [(1000, "0.85"), (1500, "1.25")],
        density=1.03,
    ),
    _ing(
        "yogur_natural",
        "Yogur natural",
        "lacteos",
        "g",
        ["milk"],
        (61, 3.5, 4.7, 4.7, 3.3, 2.1, 0, 0.1),
        [(500, "1.10"), (1000, "1.99")],
    ),
    _ing(
        "queso_curado",
        "Queso curado",
        "lacteos",
        "g",
        ["milk"],
        (402, 25, 1.4, 0.5, 33, 21, 0, 1.6),
        [(250, "3.95"), (500, "7.50")],
    ),
    _ing(
        "queso_fresco",
        "Queso fresco",
        "lacteos",
        "g",
        ["milk"],
        (98, 11, 3.5, 3.5, 5, 3, 0, 0.7),
        [(250, "1.85"), (500, "3.40")],
    ),
    _ing(
        "mantequilla",
        "Mantequilla",
        "lacteos",
        "g",
        ["milk"],
        (717, 0.9, 0.1, 0.1, 81, 51, 0, 1.1),
        [(250, "2.20"), (500, "4.10")],
    ),
    _ing(
        "nata_cocinar",
        "Nata para cocinar",
        "lacteos",
        "ml",
        ["milk"],
        (195, 2.5, 4, 3, 19, 12, 0, 0.1),
        [(500, "1.60"), (200, "0.75")],
        density=1.0,
    ),
    # --- huevos (2) ---
    _ing(
        "huevos_m",
        "Huevos M",
        "huevos",
        "unit",
        ["egg"],
        (155, 13, 1.1, 1.1, 11, 3.3, 0, 0.4),
        [(6, "1.35"), (12, "2.45")],
    ),
    _ing(
        "huevos_l",
        "Huevos L",
        "huevos",
        "unit",
        ["egg"],
        (155, 13, 1.1, 1.1, 11, 3.3, 0, 0.4),
        [(6, "1.55"), (12, "2.85")],
    ),
    # --- cereales_pasta_arroz (7) ---
    _ing(
        "arroz_redondo",
        "Arroz redondo",
        "cereales_pasta_arroz",
        "g",
        [],
        (350, 7, 78, 0.1, 0.6, 0.2, 1.4, 0),
        [(1000, "1.15"), (500, "0.65")],
    ),
    _ing(
        "arroz_basmati",
        "Arroz basmati",
        "cereales_pasta_arroz",
        "g",
        [],
        (349, 8, 76, 0.1, 0.7, 0.2, 1.3, 0),
        [(500, "1.45"), (1000, "2.70")],
    ),
    _ing(
        "pasta_macarrones",
        "Macarrones",
        "cereales_pasta_arroz",
        "g",
        ["gluten"],
        (371, 13, 75, 3, 1.5, 0.3, 3, 0),
        [(500, "0.95"), (1000, "1.79")],
    ),
    _ing(
        "pasta_espagueti",
        "Espaguetis",
        "cereales_pasta_arroz",
        "g",
        ["gluten"],
        (371, 13, 75, 3, 1.5, 0.3, 3, 0),
        [(500, "0.99"), (1000, "1.85")],
    ),
    _ing(
        "avena_copos",
        "Copos de avena",
        "cereales_pasta_arroz",
        "g",
        [],
        (389, 17, 66, 1, 7, 1.2, 10, 0),
        [(500, "1.25"), (1000, "2.30")],
        traces=["gluten"],
    ),
    _ing(
        "quinoa",
        "Quinoa",
        "cereales_pasta_arroz",
        "g",
        [],
        (368, 14, 64, 0, 6, 0.7, 7, 0),
        [(500, "2.95"), (250, "1.65")],
    ),
    _ing(
        "cuscus",
        "Cuscús",
        "cereales_pasta_arroz",
        "g",
        ["gluten"],
        (376, 13, 77, 0, 0.6, 0.1, 5, 0),
        [(500, "1.35"), (250, "0.79")],
    ),
    # --- legumbres (6) ---
    _ing(
        "garbanzos_seco",
        "Garbanzos secos",
        "legumbres",
        "g",
        [],
        (364, 19, 61, 11, 6, 0.6, 17, 0),
        [(500, "1.20"), (1000, "2.25")],
    ),
    _ing(
        "lentejas",
        "Lentejas",
        "legumbres",
        "g",
        [],
        (353, 25, 60, 2, 1.1, 0.2, 31, 0),
        [(500, "1.15"), (1000, "2.15")],
    ),
    _ing(
        "alubias_blancas",
        "Alubias blancas",
        "legumbres",
        "g",
        [],
        (333, 23, 60, 2, 0.8, 0.2, 15, 0),
        [(500, "1.30"), (1000, "2.45")],
    ),
    _ing(
        "garbanzos_cocido",
        "Garbanzos cocidos (bote)",
        "legumbres",
        "g",
        [],
        (139, 7, 22, 0.4, 2.6, 0.3, 7, 0.3),
        [(400, "0.95"), (570, "1.25")],
    ),
    _ing(
        "guisantes",
        "Guisantes",
        "legumbres",
        "g",
        [],
        (81, 5, 14, 6, 0.4, 0.1, 5, 0),
        [(500, "1.60"), (1000, "2.95")],
    ),
    _ing(
        "soja_texturizada",
        "Soja texturizada",
        "legumbres",
        "g",
        ["soy"],
        (336, 52, 30, 11, 1.5, 0.2, 18, 0),
        [(250, "2.10"), (500, "3.85")],
    ),
    # --- panaderia (5) ---
    _ing(
        "pan_barra",
        "Barra de pan",
        "panaderia",
        "g",
        ["gluten"],
        (265, 9, 49, 3, 3.2, 0.7, 2.7, 1.2),
        [(250, "0.55"), (500, "0.95")],
    ),
    _ing(
        "pan_molde",
        "Pan de molde",
        "panaderia",
        "g",
        ["gluten"],
        (265, 8, 49, 4, 3.5, 0.8, 2.5, 1.1),
        [(460, "1.15"), (680, "1.55")],
    ),
    _ing(
        "pan_integral",
        "Pan integral",
        "panaderia",
        "g",
        ["gluten"],
        (247, 10, 41, 3, 3.4, 0.7, 7, 1.1),
        [(400, "1.25"), (600, "1.75")],
    ),
    _ing(
        "tortillas_trigo",
        "Tortillas de trigo",
        "panaderia",
        "g",
        ["gluten"],
        (310, 8, 49, 2, 7, 3, 3, 1.2),
        [(320, "1.45"), (480, "1.95")],
    ),
    _ing(
        "biscotes",
        "Biscotes",
        "panaderia",
        "g",
        ["gluten"],
        (400, 11, 72, 6, 7, 1.5, 4, 1.4),
        [(270, "1.20"), (500, "1.99")],
    ),
    # --- aceites_condimentos (7) ---
    _ing(
        "aceite_oliva",
        "Aceite de oliva virgen extra",
        "aceites_condimentos",
        "ml",
        [],
        (884, 0, 0, 0, 100, 14, 0, 0),
        [(1000, "6.95"), (500, "3.75")],
        density=0.92,
    ),
    _ing(
        "aceite_girasol",
        "Aceite de girasol",
        "aceites_condimentos",
        "ml",
        [],
        (884, 0, 0, 0, 100, 11, 0, 0),
        [(1000, "1.99"), (500, "1.15")],
        density=0.92,
    ),
    _ing(
        "sal",
        "Sal",
        "aceites_condimentos",
        "g",
        [],
        (0, 0, 0, 0, 0, 0, 0, 100),
        [(1000, "0.45"), (500, "0.30")],
    ),
    _ing(
        "pimienta_negra",
        "Pimienta negra",
        "aceites_condimentos",
        "g",
        [],
        (251, 10, 64, 0.6, 3.3, 1.4, 25, 0.02),
        [(50, "1.25"), (100, "2.20")],
    ),
    _ing(
        "pimenton",
        "Pimentón",
        "aceites_condimentos",
        "g",
        [],
        (282, 14, 54, 10, 13, 2, 35, 0.07),
        [(75, "1.10"), (150, "1.95")],
    ),
    _ing(
        "comino",
        "Comino",
        "aceites_condimentos",
        "g",
        [],
        (375, 18, 44, 2.2, 22, 1.5, 11, 0.04),
        [(50, "1.15"), (100, "2.05")],
    ),
    _ing(
        "vinagre",
        "Vinagre",
        "aceites_condimentos",
        "ml",
        ["sulphite"],
        (18, 0, 0.9, 0.4, 0, 0, 0, 0),
        [(750, "0.85"), (1000, "1.10")],
        density=1.01,
    ),
    # --- frutos_secos_semillas (5) ---
    _ing(
        "almendra",
        "Almendras",
        "frutos_secos_semillas",
        "g",
        ["tree_nut"],
        (579, 21, 22, 4, 50, 3.8, 12, 0),
        [(200, "2.95"), (500, "6.90")],
    ),
    _ing(
        "nuez",
        "Nueces",
        "frutos_secos_semillas",
        "g",
        ["tree_nut"],
        (654, 15, 14, 2.6, 65, 6, 7, 0),
        [(200, "2.75"), (400, "5.20")],
    ),
    _ing(
        "anacardo",
        "Anacardos",
        "frutos_secos_semillas",
        "g",
        ["tree_nut"],
        (553, 18, 30, 6, 44, 8, 3, 0),
        [(200, "3.40"), (400, "6.50")],
    ),
    _ing(
        "cacahuete",
        "Cacahuetes",
        "frutos_secos_semillas",
        "g",
        ["peanut"],
        (567, 26, 16, 4, 49, 7, 9, 0),
        [(200, "1.85"), (500, "4.20")],
    ),
    _ing(
        "sesamo",
        "Sésamo",
        "frutos_secos_semillas",
        "g",
        ["sesame"],
        (573, 18, 23, 0.3, 50, 7, 12, 0),
        [(150, "1.65"), (300, "3.10")],
    ),
    # --- conservas_despensa (8) ---
    _ing(
        "tomate_triturado",
        "Tomate triturado",
        "conservas_despensa",
        "g",
        [],
        (32, 1.6, 7, 4.5, 0.3, 0, 1.5, 0.2),
        [(400, "0.75"), (800, "1.35")],
    ),
    _ing(
        "maiz_dulce",
        "Maíz dulce",
        "conservas_despensa",
        "g",
        [],
        (86, 3.2, 19, 6, 1.2, 0.2, 2.7, 0.3),
        [(300, "1.15"), (150, "0.69")],
    ),
    _ing(
        "aceitunas",
        "Aceitunas",
        "conservas_despensa",
        "g",
        [],
        (145, 1, 6, 0, 15, 2, 3.3, 3.3),
        [(350, "1.40"), (200, "0.95")],
    ),
    _ing(
        "harina_trigo",
        "Harina de trigo",
        "conservas_despensa",
        "g",
        ["gluten"],
        (364, 10, 76, 0.3, 1, 0.2, 2.7, 0),
        [(1000, "0.75"), (500, "0.45")],
    ),
    _ing(
        "azucar",
        "Azúcar",
        "conservas_despensa",
        "g",
        [],
        (400, 0, 100, 100, 0, 0, 0, 0),
        [(1000, "1.05"), (500, "0.65")],
    ),
    _ing(
        "miel",
        "Miel",
        "conservas_despensa",
        "g",
        [],
        (304, 0.3, 82, 82, 0, 0, 0.2, 0),
        [(500, "3.95"), (250, "2.25")],
    ),
    _ing(
        "tofu",
        "Tofu",
        "conservas_despensa",
        "g",
        ["soy"],
        (76, 8, 1.9, 0.6, 4.8, 0.7, 0.3, 0),
        [(250, "1.95"), (400, "2.95")],
    ),
    _ing(
        "leche_coco",
        "Leche de coco",
        "conservas_despensa",
        "ml",
        [],
        (230, 2.3, 6, 3, 24, 21, 2.2, 0.03),
        [(400, "1.45"), (200, "0.85")],
        density=0.97,
    ),
]


class RecipeSpec(TypedDict):
    """One synthetic recipe.

    Ingredient tuples are ``(canonical_name, quantity, optional, subgroup)``.
    """

    title: str
    description: str
    servings: int
    meal_types: list[str]
    cuisine: str
    tags: list[str]
    prep: int
    cook: int
    equipment: list[str]
    ingredients: list[tuple[str, float, bool, str | None]]
    steps: list[str]


def _r(
    title: str,
    description: str,
    servings: int,
    meal_types: list[str],
    cuisine: str,
    tags: list[str],
    prep: int,
    cook: int,
    equipment: list[str],
    ingredients: list[tuple[str, float, bool, str | None]],
    steps: list[str],
) -> RecipeSpec:
    return {
        "title": title,
        "description": description,
        "servings": servings,
        "meal_types": meal_types,
        "cuisine": cuisine,
        "tags": tags,
        "prep": prep,
        "cook": cook,
        "equipment": equipment,
        "ingredients": ingredients,
        "steps": steps,
    }


# 92 synthetic recipes. Every ``canonical_name`` below exists in INGREDIENTS,
# so every recipe is satisfiable by the seeded catalogue.
RECIPES: Final[list[RecipeSpec]] = [
    # ---------- Desayunos ----------
    _r(
        "Tostada de aguacate y tomate",
        "Pan tostado con aguacate machacado y tomate. Desayuno vegano rápido.",
        2,
        ["breakfast"],
        "mediterranea",
        ["vegan", "vegetarian", "quick"],
        8,
        4,
        ["toaster"],
        [
            ("pan_integral", 120, False, None),
            ("aguacate", 150, False, None),
            ("tomate", 100, False, None),
            ("aceite_oliva", 10, False, None),
            ("sal", 2, True, None),
        ],
        [
            "Tuesta el pan.",
            "Machaca el aguacate con sal y aceite.",
            "Extiende sobre el pan y cubre con rodajas de tomate.",
        ],
    ),
    _r(
        "Yogur con arándanos y avena",
        "Bol de yogur natural con copos de avena y arándanos frescos.",
        2,
        ["breakfast", "snack"],
        "internacional",
        ["vegetarian", "quick"],
        5,
        0,
        [],
        [
            ("yogur_natural", 300, False, None),
            ("avena_copos", 60, False, None),
            ("arandano", 80, False, None),
            ("miel", 20, True, None),
        ],
        [
            "Reparte el yogur en dos boles.",
            "Añade la avena y los arándanos.",
            "Endulza con un hilo de miel si se desea.",
        ],
    ),
    _r(
        "Tortilla de espinacas",
        "Tortilla jugosa de huevo y espinacas salteadas. Alta en proteína.",
        2,
        ["breakfast", "dinner"],
        "espanola",
        ["vegetarian", "high_protein", "quick"],
        5,
        10,
        ["stovetop"],
        [
            ("huevos_m", 4, False, None),
            ("espinaca", 120, False, None),
            ("aceite_oliva", 10, False, None),
            ("sal", 2, False, None),
        ],
        [
            "Saltea las espinacas con un poco de aceite.",
            "Bate los huevos con sal.",
            "Vierte sobre las espinacas y cuaja la tortilla por ambos lados.",
        ],
    ),
    _r(
        "Porridge de avena con plátano",
        "Copos de avena cocidos en leche con plátano en rodajas.",
        2,
        ["breakfast"],
        "internacional",
        ["vegetarian"],
        5,
        8,
        ["stovetop"],
        [
            ("avena_copos", 80, False, None),
            ("leche_entera", 400, False, "leche"),
            ("platano", 160, False, None),
            ("miel", 15, True, None),
        ],
        [
            "Calienta la leche con la avena a fuego medio.",
            "Cocina removiendo hasta espesar.",
            "Sirve con el plátano en rodajas y un toque de miel.",
        ],
    ),
    _r(
        "Tostada integral con queso fresco y tomate",
        "Pan integral con queso fresco y tomate. Ligero y rápido.",
        2,
        ["breakfast"],
        "mediterranea",
        ["vegetarian", "quick"],
        6,
        3,
        ["toaster"],
        [
            ("pan_integral", 120, False, None),
            ("queso_fresco", 120, False, None),
            ("tomate", 100, False, None),
            ("aceite_oliva", 8, True, None),
        ],
        [
            "Tuesta el pan integral.",
            "Coloca lonchas de queso fresco.",
            "Cubre con tomate y aliña con aceite.",
        ],
    ),
    _r(
        "Huevos revueltos con pan",
        "Huevos revueltos cremosos acompañados de pan tostado.",
        2,
        ["breakfast"],
        "internacional",
        ["vegetarian", "high_protein", "quick"],
        3,
        6,
        ["stovetop"],
        [
            ("huevos_m", 4, False, None),
            ("mantequilla", 15, False, None),
            ("pan_barra", 120, False, None),
            ("sal", 2, False, None),
        ],
        [
            "Bate los huevos con sal.",
            "Cuaja a fuego suave con la mantequilla removiendo.",
            "Sirve con el pan tostado.",
        ],
    ),
    _r(
        "Bol de yogur con fresa y almendras",
        "Yogur con fresas troceadas y almendras. Bajo en calorías.",
        2,
        ["breakfast", "snack"],
        "internacional",
        ["vegetarian", "quick", "low_calorie"],
        5,
        0,
        [],
        [
            ("yogur_natural", 300, False, None),
            ("fresa", 150, False, None),
            ("almendra", 30, False, None),
        ],
        ["Reparte el yogur.", "Añade las fresas troceadas y las almendras."],
    ),
    _r(
        "Tostada de pan con miel y nueces",
        "Tostada dulce con miel y nueces picadas.",
        2,
        ["breakfast"],
        "internacional",
        ["vegetarian", "quick"],
        4,
        3,
        ["toaster"],
        [("pan_molde", 120, False, None), ("miel", 30, False, None), ("nuez", 30, False, None)],
        ["Tuesta el pan de molde.", "Unta con miel y reparte las nueces picadas."],
    ),
    _r(
        "Tortilla de patata",
        "Clásica tortilla española de patata y cebolla. Para toda la familia.",
        4,
        ["breakfast", "dinner"],
        "espanola",
        ["vegetarian", "family"],
        15,
        25,
        ["stovetop"],
        [
            ("patata", 600, False, None),
            ("cebolla", 150, False, None),
            ("huevos_l", 6, False, None),
            ("aceite_oliva", 40, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Pela y corta las patatas y la cebolla.",
            "Fríelas a fuego suave hasta que estén tiernas.",
            "Bate los huevos, mézclalos con la patata y cuaja la tortilla por ambas caras.",
        ],
    ),
    _r(
        "Batido de plátano y avena",
        "Bebida cremosa de plátano, avena y leche. Rápido y saciante.",
        2,
        ["breakfast", "snack"],
        "internacional",
        ["vegetarian", "quick"],
        5,
        0,
        ["blender"],
        [
            ("platano", 200, False, None),
            ("avena_copos", 40, False, None),
            ("leche_desnatada", 400, False, "leche"),
        ],
        ["Pela el plátano.", "Tritura todo en la batidora hasta que quede homogéneo."],
    ),
    # ---------- Comidas / cenas ----------
    _r(
        "Arroz con pollo y verduras",
        "Arroz salteado con pechuga de pollo, pimiento y zanahoria.",
        4,
        ["lunch"],
        "mediterranea",
        ["high_protein", "family"],
        15,
        25,
        ["stovetop"],
        [
            ("arroz_redondo", 320, False, None),
            ("pollo_pechuga", 500, False, None),
            ("pimiento_rojo", 200, False, None),
            ("zanahoria", 150, False, None),
            ("cebolla", 100, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Dora el pollo troceado.",
            "Añade las verduras y sofríe.",
            "Incorpora el arroz y agua, y cuece hasta que absorba el líquido.",
        ],
    ),
    _r(
        "Salteado de ternera con pimiento y arroz",
        "Tiras de ternera salteadas con pimiento sobre arroz basmati.",
        4,
        ["lunch", "dinner"],
        "asiatica",
        ["high_protein"],
        15,
        15,
        ["stovetop"],
        [
            ("ternera_picada", 500, False, None),
            ("pimiento_rojo", 200, False, None),
            ("cebolla", 100, False, None),
            ("arroz_basmati", 300, False, None),
            ("aceite_girasol", 20, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Cuece el arroz basmati.",
            "Saltea la ternera a fuego fuerte.",
            "Añade el pimiento y la cebolla y sirve sobre el arroz.",
        ],
    ),
    _r(
        "Merluza al horno con patata",
        "Lomos de merluza al horno sobre cama de patata. Ligero.",
        4,
        ["dinner"],
        "espanola",
        ["high_protein", "low_calorie"],
        15,
        30,
        ["oven"],
        [
            ("merluza", 600, False, None),
            ("patata", 600, False, None),
            ("cebolla", 100, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Corta las patatas en rodajas y hornéalas 15 min.",
            "Coloca la merluza encima, aliña y hornea 15 min más.",
        ],
    ),
    _r(
        "Salmón a la plancha con espinacas",
        "Salmón a la plancha con espinacas salteadas. Rico en proteína.",
        2,
        ["dinner"],
        "internacional",
        ["high_protein", "quick"],
        5,
        12,
        ["stovetop"],
        [
            ("salmon", 300, False, None),
            ("espinaca", 200, False, None),
            ("ajo", 10, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Marca el salmón a la plancha por ambos lados.",
            "Saltea las espinacas con ajo y sirve junto al salmón.",
        ],
    ),
    _r(
        "Espaguetis con tomate y albahaca",
        "Espaguetis con salsa de tomate casera. Plato familiar.",
        4,
        ["lunch"],
        "italiana",
        ["vegetarian", "vegan", "family"],
        5,
        20,
        ["stovetop"],
        [
            ("pasta_espagueti", 400, False, None),
            ("tomate_triturado", 400, False, None),
            ("ajo", 10, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Cuece los espaguetis al dente.",
            "Sofríe el ajo y añade el tomate triturado.",
            "Mezcla la pasta con la salsa.",
        ],
    ),
    _r(
        "Macarrones con atún",
        "Macarrones con salsa de tomate y atún. Rápido y familiar.",
        4,
        ["lunch"],
        "mediterranea",
        ["high_protein", "quick", "family"],
        5,
        15,
        ["stovetop"],
        [
            ("pasta_macarrones", 400, False, None),
            ("atun_lata", 150, False, None),
            ("tomate_triturado", 400, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Cuece los macarrones.",
            "Calienta el tomate y añade el atún escurrido.",
            "Mezcla con la pasta.",
        ],
    ),
    _r(
        "Lentejas guisadas con zanahoria",
        "Guiso tradicional de lentejas con verduras. Vegano y saciante.",
        4,
        ["lunch"],
        "espanola",
        ["vegan", "vegetarian", "high_protein", "family"],
        15,
        40,
        ["stovetop"],
        [
            ("lentejas", 400, False, None),
            ("zanahoria", 150, False, None),
            ("cebolla", 100, False, None),
            ("ajo", 10, False, None),
            ("pimenton", 5, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Sofríe cebolla, ajo y zanahoria.",
            "Añade el pimentón y las lentejas.",
            "Cubre con agua y cuece a fuego lento hasta que estén tiernas.",
        ],
    ),
    _r(
        "Garbanzos con espinacas",
        "Garbanzos guisados con espinacas y pimentón. Vegano.",
        4,
        ["lunch"],
        "espanola",
        ["vegan", "vegetarian", "high_protein"],
        10,
        20,
        ["stovetop"],
        [
            ("garbanzos_cocido", 570, False, None),
            ("espinaca", 300, False, None),
            ("ajo", 10, False, None),
            ("pimenton", 5, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Sofríe el ajo con pimentón.",
            "Añade las espinacas hasta que reduzcan.",
            "Incorpora los garbanzos escurridos y calienta.",
        ],
    ),
    _r(
        "Ensalada de garbanzos y tomate",
        "Ensalada fría de garbanzos, tomate y cebolla. Rápida y ligera.",
        2,
        ["lunch"],
        "mediterranea",
        ["vegan", "vegetarian", "quick", "low_calorie"],
        10,
        0,
        [],
        [
            ("garbanzos_cocido", 400, False, None),
            ("tomate", 200, False, None),
            ("cebolla", 60, False, None),
            ("aceite_oliva", 15, False, None),
            ("vinagre", 10, True, None),
        ],
        [
            "Escurre los garbanzos.",
            "Trocea el tomate y la cebolla.",
            "Mezcla todo y aliña con aceite y vinagre.",
        ],
    ),
    _r(
        "Crema de calabacín",
        "Crema suave de calabacín y cebolla. Baja en calorías.",
        4,
        ["dinner"],
        "mediterranea",
        ["vegetarian", "low_calorie"],
        10,
        25,
        ["stovetop", "blender"],
        [
            ("calabacin", 800, False, None),
            ("cebolla", 100, False, None),
            ("patata", 150, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Sofríe la cebolla.",
            "Añade calabacín y patata con agua y cuece 20 min.",
            "Tritura hasta obtener una crema fina.",
        ],
    ),
    _r(
        "Pollo al horno con pimientos",
        "Muslos de pollo asados con pimiento y cebolla. Familiar.",
        4,
        ["lunch", "dinner"],
        "mediterranea",
        ["high_protein", "family"],
        15,
        40,
        ["oven"],
        [
            ("pollo_muslo", 800, False, None),
            ("pimiento_rojo", 300, False, None),
            ("cebolla", 150, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Coloca el pollo y las verduras en una bandeja.",
            "Aliña con aceite y sal.",
            "Hornea a 200°C durante 40 minutos.",
        ],
    ),
    _r(
        "Pavo a la plancha con ensalada",
        "Filetes de pavo con ensalada fresca. Ligero y proteico.",
        2,
        ["dinner"],
        "internacional",
        ["high_protein", "quick", "low_calorie"],
        8,
        8,
        ["stovetop"],
        [
            ("pavo_pechuga", 300, False, None),
            ("tomate", 150, False, None),
            ("espinaca", 100, False, None),
            ("aceite_oliva", 10, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Haz el pavo a la plancha.",
            "Prepara una ensalada de espinaca y tomate.",
            "Sirve el pavo sobre la ensalada.",
        ],
    ),
    _r(
        "Quinoa con verduras salteadas",
        "Quinoa con calabacín, pimiento y zanahoria. Vegano y proteico.",
        4,
        ["lunch"],
        "internacional",
        ["vegan", "vegetarian", "high_protein"],
        10,
        20,
        ["stovetop"],
        [
            ("quinoa", 300, False, None),
            ("calabacin", 200, False, None),
            ("pimiento_rojo", 150, False, None),
            ("zanahoria", 100, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Cuece la quinoa.",
            "Saltea las verduras troceadas.",
            "Mezcla la quinoa con las verduras.",
        ],
    ),
    _r(
        "Cuscús con garbanzos y verduras",
        "Cuscús esponjoso con garbanzos y verdura. Vegano y familiar.",
        4,
        ["lunch"],
        "arabe",
        ["vegan", "vegetarian", "family"],
        10,
        15,
        ["stovetop"],
        [
            ("cuscus", 300, False, None),
            ("garbanzos_cocido", 400, False, None),
            ("zanahoria", 100, False, None),
            ("calabacin", 150, False, None),
            ("comino", 4, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Hidrata el cuscús con agua caliente.",
            "Saltea las verduras con comino.",
            "Mezcla el cuscús con las verduras y los garbanzos.",
        ],
    ),
    _r(
        "Guiso de alubias blancas",
        "Alubias blancas guisadas con verduras. Vegano y familiar.",
        4,
        ["lunch"],
        "espanola",
        ["vegan", "vegetarian", "family", "high_protein"],
        15,
        45,
        ["stovetop"],
        [
            ("alubias_blancas", 400, False, None),
            ("cebolla", 100, False, None),
            ("zanahoria", 100, False, None),
            ("ajo", 10, False, None),
            ("pimenton", 5, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Sofríe cebolla, ajo y zanahoria.",
            "Añade pimentón y las alubias.",
            "Cubre con agua y cuece a fuego lento hasta que estén tiernas.",
        ],
    ),
    _r(
        "Tofu salteado con arroz basmati",
        "Tofu dorado salteado con verduras sobre arroz basmati. Vegano.",
        2,
        ["dinner"],
        "asiatica",
        ["vegan", "vegetarian", "high_protein"],
        10,
        15,
        ["stovetop"],
        [
            ("tofu", 250, False, None),
            ("arroz_basmati", 150, False, None),
            ("pimiento_rojo", 100, False, None),
            ("cebolla", 60, False, None),
            ("aceite_girasol", 15, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Cuece el arroz basmati.",
            "Dora el tofu en dados.",
            "Añade las verduras, saltea y sirve sobre el arroz.",
        ],
    ),
    _r(
        "Gambas al ajillo con pan",
        "Gambas salteadas con ajo y aceite, con pan para mojar.",
        2,
        ["dinner"],
        "espanola",
        ["high_protein", "quick"],
        8,
        8,
        ["stovetop"],
        [
            ("gambas", 300, False, None),
            ("ajo", 15, False, None),
            ("aceite_oliva", 30, False, None),
            ("pan_barra", 120, False, None),
            ("sal", 2, False, None),
        ],
        [
            "Calienta el aceite con el ajo laminado.",
            "Añade las gambas y saltea 3 min.",
            "Sirve con pan para mojar.",
        ],
    ),
    _r(
        "Mejillones al vapor con limón",
        "Mejillones abiertos al vapor con un toque de limón. Ligero.",
        2,
        ["dinner"],
        "espanola",
        ["high_protein", "quick", "low_calorie"],
        5,
        10,
        ["stovetop"],
        [("mejillones", 1000, False, None), ("limon", 100, False, None), ("sal", 2, True, None)],
        [
            "Limpia los mejillones.",
            "Cuécelos al vapor hasta que se abran.",
            "Sirve con zumo de limón.",
        ],
    ),
    _r(
        "Bacalao con garbanzos",
        "Bacalao desmigado con garbanzos y espinacas. Proteico.",
        4,
        ["lunch"],
        "espanola",
        ["high_protein"],
        15,
        25,
        ["stovetop"],
        [
            ("bacalao", 400, False, None),
            ("garbanzos_cocido", 400, False, None),
            ("espinaca", 150, False, None),
            ("ajo", 10, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Sofríe el ajo.",
            "Añade espinacas y bacalao desmigado.",
            "Incorpora los garbanzos y calienta.",
        ],
    ),
    _r(
        "Lomo de cerdo al horno con patata",
        "Lomo de cerdo asado con patatas. Plato familiar.",
        4,
        ["lunch"],
        "espanola",
        ["high_protein", "family"],
        15,
        45,
        ["oven"],
        [
            ("cerdo_lomo", 600, False, None),
            ("patata", 600, False, None),
            ("cebolla", 100, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Coloca el lomo y las patatas en la bandeja.",
            "Aliña con aceite y sal.",
            "Hornea a 190°C durante 45 minutos.",
        ],
    ),
    _r(
        "Hamburguesa de ternera casera con pan",
        "Hamburguesa de ternera con cebolla y tomate en pan.",
        4,
        ["dinner"],
        "internacional",
        ["high_protein", "family"],
        15,
        12,
        ["stovetop"],
        [
            ("ternera_picada", 500, False, None),
            ("pan_molde", 200, False, None),
            ("tomate", 150, False, None),
            ("cebolla", 80, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Forma las hamburguesas con la carne y sal.",
            "Cocínalas a la plancha.",
            "Monta con pan, tomate y cebolla.",
        ],
    ),
    _r(
        "Pisto de verduras con huevo",
        "Pisto de calabacín, pimiento y tomate coronado con huevo.",
        4,
        ["dinner"],
        "espanola",
        ["vegetarian", "family", "low_calorie"],
        15,
        30,
        ["stovetop"],
        [
            ("calabacin", 300, False, None),
            ("pimiento_rojo", 200, False, None),
            ("tomate_triturado", 400, False, None),
            ("cebolla", 100, False, None),
            ("huevos_m", 4, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Sofríe la cebolla y el pimiento.",
            "Añade el calabacín y el tomate y cuece 20 min.",
            "Sirve con un huevo a la plancha por ración.",
        ],
    ),
    _r(
        "Ensalada de pasta con atún y maíz",
        "Ensalada fría de macarrones con atún, maíz y tomate.",
        4,
        ["lunch"],
        "internacional",
        ["quick", "family"],
        10,
        12,
        ["stovetop"],
        [
            ("pasta_macarrones", 350, False, None),
            ("atun_lata", 150, False, None),
            ("maiz_dulce", 150, False, None),
            ("tomate", 150, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Cuece la pasta y enfríala.",
            "Mezcla con atún, maíz y tomate.",
            "Aliña con aceite y sal.",
        ],
    ),
    _r(
        "Crema de zanahoria",
        "Crema aterciopelada de zanahoria y cebolla. Vegana y ligera.",
        4,
        ["dinner"],
        "mediterranea",
        ["vegan", "vegetarian", "low_calorie"],
        10,
        25,
        ["stovetop", "blender"],
        [
            ("zanahoria", 700, False, None),
            ("cebolla", 100, False, None),
            ("patata", 150, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Sofríe la cebolla.",
            "Añade zanahoria y patata con agua y cuece 20 min.",
            "Tritura hasta que quede fina.",
        ],
    ),
    _r(
        "Revuelto de calabacín",
        "Revuelto jugoso de huevo y calabacín. Rápido y proteico.",
        2,
        ["dinner"],
        "espanola",
        ["vegetarian", "quick", "high_protein"],
        5,
        10,
        ["stovetop"],
        [
            ("calabacin", 300, False, None),
            ("huevos_m", 4, False, None),
            ("ajo", 8, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Saltea el calabacín en dados con ajo.",
            "Añade los huevos batidos.",
            "Remueve hasta cuajar el revuelto.",
        ],
    ),
    _r(
        "Salteado de soja texturizada con verduras",
        "Soja texturizada hidratada y salteada con verduras. Vegano y proteico.",
        4,
        ["lunch"],
        "asiatica",
        ["vegan", "vegetarian", "high_protein"],
        15,
        15,
        ["stovetop"],
        [
            ("soja_texturizada", 200, False, None),
            ("pimiento_rojo", 150, False, None),
            ("cebolla", 100, False, None),
            ("zanahoria", 100, False, None),
            ("aceite_girasol", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Hidrata la soja texturizada en agua caliente.",
            "Saltea las verduras.",
            "Añade la soja escurrida y saltea todo junto.",
        ],
    ),
    _r(
        "Pollo al curry con arroz basmati",
        "Pollo en salsa de leche de coco y pimentón sobre arroz basmati.",
        4,
        ["lunch"],
        "asiatica",
        ["high_protein", "family"],
        15,
        25,
        ["stovetop"],
        [
            ("pollo_pechuga", 500, False, None),
            ("leche_coco", 400, False, None),
            ("cebolla", 100, False, None),
            ("pimenton", 6, False, None),
            ("arroz_basmati", 300, False, None),
            ("aceite_girasol", 15, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Cuece el arroz basmati.",
            "Dora el pollo con la cebolla.",
            "Añade la leche de coco y el pimentón, y cuece hasta espesar.",
        ],
    ),
    _r(
        "Espaguetis con gambas",
        "Espaguetis salteados con gambas y ajo. Proteico.",
        2,
        ["dinner"],
        "italiana",
        ["high_protein"],
        10,
        15,
        ["stovetop"],
        [
            ("pasta_espagueti", 200, False, None),
            ("gambas", 250, False, None),
            ("ajo", 12, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 3, False, None),
        ],
        ["Cuece los espaguetis.", "Saltea las gambas con ajo.", "Mezcla la pasta con las gambas."],
    ),
    _r(
        "Ensalada mediterránea",
        "Ensalada de tomate, aceitunas y queso fresco. Rápida y ligera.",
        2,
        ["lunch"],
        "mediterranea",
        ["vegetarian", "quick", "low_calorie"],
        10,
        0,
        [],
        [
            ("tomate", 250, False, None),
            ("aceitunas", 60, False, None),
            ("queso_fresco", 120, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 2, True, None),
        ],
        ["Trocea el tomate y el queso.", "Añade las aceitunas.", "Aliña con aceite y sal."],
    ),
    _r(
        "Wrap de pollo",
        "Tortilla de trigo rellena de pollo y verduras. Rápido.",
        2,
        ["lunch"],
        "internacional",
        ["high_protein", "quick"],
        10,
        10,
        ["stovetop"],
        [
            ("tortillas_trigo", 160, False, None),
            ("pollo_pechuga", 250, False, None),
            ("tomate", 100, False, None),
            ("espinaca", 60, False, None),
            ("aceite_oliva", 10, False, None),
        ],
        [
            "Haz el pollo en tiras a la plancha.",
            "Rellena las tortillas con pollo, tomate y espinaca.",
            "Enrolla los wraps.",
        ],
    ),
    # ---------- Meriendas / snacks ----------
    _r(
        "Manzana con crema de cacahuete",
        "Rodajas de manzana con cacahuete machacado. Merienda vegana.",
        2,
        ["snack"],
        "internacional",
        ["vegan", "vegetarian", "quick"],
        5,
        0,
        [],
        [("manzana", 200, False, None), ("cacahuete", 40, False, None)],
        ["Corta la manzana en rodajas.", "Acompaña con cacahuetes machacados."],
    ),
    _r(
        "Mix de almendras y nueces",
        "Puñado de almendras y nueces. Merienda proteica y vegana.",
        2,
        ["snack"],
        "internacional",
        ["vegan", "vegetarian", "quick", "high_protein"],
        2,
        0,
        [],
        [("almendra", 40, False, "frutos_secos"), ("nuez", 40, False, "frutos_secos")],
        ["Mezcla las almendras y las nueces y reparte en dos raciones."],
    ),
    _r(
        "Yogur con miel y nueces",
        "Yogur natural con miel y nueces. Merienda rápida.",
        2,
        ["snack"],
        "internacional",
        ["vegetarian", "quick"],
        5,
        0,
        [],
        [("yogur_natural", 250, False, None), ("miel", 20, False, None), ("nuez", 30, False, None)],
        ["Reparte el yogur.", "Añade miel y nueces picadas."],
    ),
    _r(
        "Tostada de pan con tomate y aceite",
        "Pan tostado con tomate rallado y aceite de oliva. Vegano.",
        2,
        ["snack"],
        "espanola",
        ["vegan", "vegetarian", "quick"],
        5,
        3,
        ["toaster"],
        [
            ("pan_barra", 120, False, None),
            ("tomate", 120, False, None),
            ("aceite_oliva", 12, False, None),
            ("sal", 2, True, None),
        ],
        ["Tuesta el pan.", "Ralla el tomate y extiéndelo.", "Aliña con aceite y sal."],
    ),
    _r(
        "Palitos de zanahoria con hummus",
        "Zanahoria en bastones con hummus casero de garbanzos. Vegano y ligero.",
        2,
        ["snack"],
        "arabe",
        ["vegan", "vegetarian", "low_calorie"],
        10,
        0,
        ["blender"],
        [
            ("zanahoria", 200, False, None),
            ("garbanzos_cocido", 200, False, None),
            ("sesamo", 20, False, None),
            ("limon", 30, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 2, False, None),
        ],
        [
            "Tritura garbanzos, sésamo, limón, aceite y sal.",
            "Corta la zanahoria en bastones y sirve con el hummus.",
        ],
    ),
    _r(
        "Plátano con nueces",
        "Plátano en rodajas con nueces. Merienda vegana rápida.",
        2,
        ["snack"],
        "internacional",
        ["vegan", "vegetarian", "quick"],
        3,
        0,
        [],
        [("platano", 200, False, None), ("nuez", 30, False, None)],
        ["Corta el plátano.", "Reparte las nueces por encima."],
    ),
    _r(
        "Queso fresco con arándanos",
        "Queso fresco con arándanos. Merienda ligera y proteica.",
        2,
        ["snack"],
        "internacional",
        ["vegetarian", "quick", "low_calorie"],
        5,
        0,
        [],
        [("queso_fresco", 200, False, None), ("arandano", 100, False, None)],
        ["Reparte el queso fresco.", "Cubre con los arándanos."],
    ),
    _r(
        "Naranja y almendras",
        "Gajos de naranja con almendras. Merienda ligera y vegana.",
        2,
        ["snack"],
        "internacional",
        ["vegan", "vegetarian", "quick", "low_calorie"],
        5,
        0,
        [],
        [("naranja", 300, False, None), ("almendra", 30, False, None)],
        ["Pela y separa la naranja en gajos.", "Acompaña con almendras."],
    ),
    _r(
        "Biscotes con queso y pavo",
        "Biscotes con queso curado y pavo. Merienda proteica y rápida.",
        2,
        ["snack"],
        "internacional",
        ["high_protein", "quick"],
        5,
        0,
        [],
        [
            ("biscotes", 80, False, None),
            ("queso_curado", 60, False, None),
            ("pavo_pechuga", 80, False, None),
        ],
        ["Coloca sobre los biscotes el queso.", "Añade lonchas de pavo."],
    ),
    _r(
        "Ensalada de frutas",
        "Macedonia de manzana, naranja, fresa y plátano. Vegana y ligera.",
        4,
        ["snack"],
        "internacional",
        ["vegan", "vegetarian", "quick", "low_calorie"],
        12,
        0,
        [],
        [
            ("manzana", 200, False, None),
            ("naranja", 200, False, None),
            ("fresa", 150, False, None),
            ("platano", 150, False, None),
        ],
        ["Pela y trocea toda la fruta.", "Mézclala en un bol y sirve fría."],
    ),
    # ---------- Ampliación: desayunos ----------
    _r(
        "Pan integral con tomate y aceite",
        "Tostada de pan integral frotada con tomate y un hilo de aceite de oliva.",
        2,
        ["breakfast"],
        "espanola",
        ["vegan", "vegetarian", "quick"],
        6,
        3,
        ["toaster"],
        [
            ("pan_integral", 120, False, None),
            ("tomate", 120, False, None),
            ("aceite_oliva", 12, False, None),
            ("sal", 2, True, None),
        ],
        [
            "Tuesta las rebanadas de pan.",
            "Frota el tomate maduro sobre el pan.",
            "Riega con aceite y sazona con sal.",
        ],
    ),
    _r(
        "Batido verde de manzana y espinaca",
        "Batido vegano de espinaca, manzana y plátano con zumo de naranja. Refrescante.",
        2,
        ["breakfast", "snack"],
        "internacional",
        ["vegan", "vegetarian", "quick", "low_calorie"],
        6,
        0,
        ["blender"],
        [
            ("espinaca", 60, False, None),
            ("manzana", 150, False, None),
            ("platano", 120, False, None),
            ("naranja", 200, False, None),
        ],
        [
            "Exprime la naranja y ponla en la batidora.",
            "Añade la espinaca, la manzana y el plátano troceados.",
            "Tritura hasta que quede homogéneo y sirve frío.",
        ],
    ),
    _r(
        "Huevos revueltos con jamón",
        "Huevos revueltos jugosos con taquitos de jamón cocido. Alto en proteína.",
        2,
        ["breakfast", "dinner"],
        "espanola",
        ["high_protein", "quick"],
        4,
        6,
        ["stovetop"],
        [
            ("huevos_m", 4, False, None),
            ("jamon_cocido", 80, False, None),
            ("aceite_oliva", 8, False, None),
            ("sal", 2, False, None),
        ],
        [
            "Trocea el jamón y dóralo un minuto en la sartén.",
            "Bate los huevos con sal y añádelos.",
            "Remueve a fuego suave hasta que cuajen cremosos.",
        ],
    ),
    _r(
        "Tortitas de avena y plátano",
        "Tortitas caseras de avena, plátano y huevo, sin harinas refinadas.",
        2,
        ["breakfast"],
        "internacional",
        ["vegetarian", "high_protein"],
        10,
        8,
        ["stovetop", "blender"],
        [
            ("avena_copos", 80, False, None),
            ("platano", 150, False, None),
            ("huevos_m", 2, False, None),
            ("leche_entera", 60, False, None),
            ("aceite_girasol", 6, False, None),
        ],
        [
            "Tritura la avena, el plátano, los huevos y la leche.",
            "Cuaja pequeñas tortitas en la sartén con un poco de aceite.",
            "Dale la vuelta cuando aparezcan burbujas y dora el otro lado.",
        ],
    ),
    _r(
        "Yogur con nueces y miel",
        "Bol de yogur natural con nueces troceadas y un hilo de miel.",
        2,
        ["breakfast", "snack"],
        "internacional",
        ["vegetarian", "quick"],
        4,
        0,
        [],
        [
            ("yogur_natural", 300, False, None),
            ("nuez", 40, False, None),
            ("miel", 20, False, None),
        ],
        [
            "Reparte el yogur en dos boles.",
            "Añade las nueces troceadas.",
            "Termina con un hilo de miel.",
        ],
    ),
    _r(
        "Tostada de aguacate y huevo",
        "Pan tostado con aguacate machacado y huevo a la plancha. Desayuno completo.",
        2,
        ["breakfast"],
        "internacional",
        ["vegetarian", "high_protein"],
        8,
        6,
        ["toaster", "stovetop"],
        [
            ("pan_integral", 120, False, None),
            ("aguacate", 150, False, None),
            ("huevos_m", 2, False, None),
            ("aceite_oliva", 8, False, None),
            ("sal", 2, True, None),
        ],
        [
            "Tuesta el pan y machaca el aguacate por encima.",
            "Cuaja los huevos a la plancha con un poco de aceite.",
            "Coloca un huevo sobre cada tostada y sazona.",
        ],
    ),
    _r(
        "Avena cocida con manzana",
        "Porridge templado de copos de avena cocidos en leche con manzana en dados.",
        2,
        ["breakfast"],
        "internacional",
        ["vegetarian", "family"],
        5,
        8,
        ["stovetop"],
        [
            ("avena_copos", 80, False, None),
            ("leche_entera", 400, False, None),
            ("manzana", 150, False, None),
            ("miel", 15, True, None),
        ],
        [
            "Cuece la avena con la leche a fuego suave removiendo.",
            "Añade la manzana en dados y cocina un par de minutos.",
            "Sirve templado con un hilo de miel.",
        ],
    ),
    _r(
        "Smoothie de fresa y plátano",
        "Batido ligero de fresa, plátano y leche de coco. Vegano y refrescante.",
        2,
        ["breakfast", "snack"],
        "internacional",
        ["vegan", "vegetarian", "quick", "low_calorie"],
        6,
        0,
        ["blender"],
        [
            ("fresa", 200, False, None),
            ("platano", 150, False, None),
            ("leche_coco", 200, False, None),
            ("naranja", 150, True, None),
        ],
        [
            "Pela la fruta y ponla en la batidora con la leche de coco.",
            "Tritura hasta que quede homogéneo.",
            "Sirve bien frío.",
        ],
    ),
    # ---------- Ampliación: comidas ----------
    _r(
        "Arroz caldoso de merluza",
        "Arroz caldoso con merluza, guisantes y tomate. Un plato marinero para la familia.",
        4,
        ["lunch", "dinner"],
        "espanola",
        ["high_protein", "family"],
        15,
        30,
        ["stovetop"],
        [
            ("arroz_redondo", 320, False, None),
            ("merluza", 400, False, None),
            ("guisantes", 150, False, None),
            ("tomate_triturado", 200, False, None),
            ("cebolla", 100, False, None),
            ("ajo", 10, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Sofríe la cebolla y el ajo, añade el tomate.",
            "Incorpora el arroz y cúbrelo con abundante agua o caldo.",
            "A media cocción añade los guisantes y la merluza en trozos.",
        ],
    ),
    _r(
        "Lentejas estofadas con verduras",
        "Guiso tradicional de lentejas con zanahoria, patata y pimentón. Vegano y saciante.",
        4,
        ["lunch"],
        "espanola",
        ["vegan", "vegetarian", "high_protein", "family"],
        15,
        35,
        ["stovetop"],
        [
            ("lentejas", 320, False, None),
            ("zanahoria", 150, False, None),
            ("patata", 200, False, None),
            ("cebolla", 100, False, None),
            ("ajo", 10, False, None),
            ("pimenton", 4, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Sofríe la cebolla y el ajo con el pimentón.",
            "Añade las lentejas, la zanahoria y la patata en dados.",
            "Cubre con agua y cuece a fuego lento hasta que estén tiernas.",
        ],
    ),
    _r(
        "Ensalada de garbanzos y atún",
        "Ensalada fría de garbanzos, atún, tomate y maíz. Vuelta y vuelta, sin cocinar.",
        4,
        ["lunch", "snack"],
        "mediterranea",
        ["high_protein", "quick"],
        12,
        0,
        [],
        [
            ("garbanzos_cocido", 400, False, None),
            ("atun_lata", 160, False, None),
            ("tomate", 150, False, None),
            ("maiz_dulce", 120, False, None),
            ("cebolla", 60, False, None),
            ("vinagre", 10, False, None),
            ("aceite_oliva", 18, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Escurre los garbanzos y el atún.",
            "Trocea el tomate y la cebolla.",
            "Mezcla todo con el maíz y aliña con aceite, vinagre y sal.",
        ],
    ),
    _r(
        "Macarrones con tomate y atún",
        "Macarrones con salsa de tomate casera y atún. Rápido y del gusto de todos.",
        4,
        ["lunch"],
        "italiana",
        ["high_protein", "quick", "family"],
        8,
        18,
        ["stovetop"],
        [
            ("pasta_macarrones", 320, False, None),
            ("tomate_triturado", 300, False, None),
            ("atun_lata", 160, False, None),
            ("cebolla", 80, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Cuece la pasta en agua con sal.",
            "Sofríe la cebolla y añade el tomate para hacer la salsa.",
            "Incorpora el atún escurrido y mezcla con los macarrones.",
        ],
    ),
    _r(
        "Cuscús con verduras asadas",
        "Cuscús esponjoso con calabacín, pimiento y zanahoria asados al horno.",
        4,
        ["lunch"],
        "arabe",
        ["vegan", "vegetarian"],
        15,
        25,
        ["oven", "stovetop"],
        [
            ("cuscus", 300, False, None),
            ("calabacin", 200, False, None),
            ("pimiento_rojo", 150, False, None),
            ("zanahoria", 150, False, None),
            ("aceite_oliva", 20, False, None),
            ("comino", 3, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Asa las verduras troceadas con aceite y comino.",
            "Hidrata el cuscús con agua caliente y sal.",
            "Mezcla el cuscús con las verduras asadas.",
        ],
    ),
    _r(
        "Pollo al horno con patatas",
        "Muslos de pollo asados con patatas panadera. Un asado familiar sencillo.",
        4,
        ["lunch", "dinner"],
        "espanola",
        ["high_protein", "family"],
        15,
        45,
        ["oven"],
        [
            ("pollo_muslo", 600, False, None),
            ("patata", 500, False, None),
            ("cebolla", 150, False, None),
            ("ajo", 12, False, None),
            ("aceite_oliva", 25, False, None),
            ("pimenton", 4, True, None),
            ("sal", 5, False, None),
        ],
        [
            "Coloca las patatas y la cebolla en la bandeja.",
            "Pon encima los muslos, riega con aceite y sazona.",
            "Asa a 200 °C unos 45 minutos hasta que el pollo esté dorado.",
        ],
    ),
    _r(
        "Ensalada de quinoa y aguacate",
        "Quinoa fría con aguacate, maíz y tomate. Ensalada vegana rica en proteína.",
        2,
        ["lunch"],
        "internacional",
        ["vegan", "vegetarian", "high_protein", "low_calorie"],
        15,
        15,
        ["stovetop"],
        [
            ("quinoa", 160, False, None),
            ("aguacate", 150, False, None),
            ("maiz_dulce", 120, False, None),
            ("tomate", 150, False, None),
            ("limon", 30, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Cuece la quinoa y déjala enfriar.",
            "Trocea el aguacate y el tomate.",
            "Mezcla todo con maíz, zumo de limón, aceite y sal.",
        ],
    ),
    _r(
        "Alubias blancas con verduras",
        "Guiso ligero de alubias blancas con calabacín, zanahoria y tomate. Vegano.",
        4,
        ["lunch"],
        "espanola",
        ["vegan", "vegetarian", "high_protein", "family"],
        10,
        25,
        ["stovetop"],
        [
            ("alubias_blancas", 500, False, None),
            ("calabacin", 200, False, None),
            ("zanahoria", 150, False, None),
            ("tomate_triturado", 200, False, None),
            ("cebolla", 100, False, None),
            ("aceite_oliva", 18, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Sofríe la cebolla con la zanahoria y el calabacín.",
            "Añade el tomate y cocina unos minutos.",
            "Incorpora las alubias y cuece a fuego lento 10 minutos.",
        ],
    ),
    _r(
        "Arroz tres delicias",
        "Arroz salteado con guisantes, zanahoria, jamón y huevo. Un básico familiar.",
        4,
        ["lunch", "dinner"],
        "asiatica",
        ["high_protein", "family"],
        15,
        20,
        ["stovetop"],
        [
            ("arroz_basmati", 320, False, None),
            ("guisantes", 150, False, None),
            ("zanahoria", 120, False, None),
            ("jamon_cocido", 120, False, None),
            ("huevos_m", 2, False, None),
            ("maiz_dulce", 100, False, None),
            ("aceite_girasol", 18, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Cuece el arroz y resérvalo.",
            "Haz un revuelto con los huevos y saltea las verduras.",
            "Añade el arroz, el jamón y el maíz y saltea todo junto.",
        ],
    ),
    _r(
        "Espaguetis a la boloñesa",
        "Espaguetis con salsa de carne picada y tomate. Un clásico que gusta a toda la casa.",
        4,
        ["lunch", "dinner"],
        "italiana",
        ["high_protein", "family"],
        12,
        30,
        ["stovetop"],
        [
            ("pasta_espagueti", 320, False, None),
            ("ternera_picada", 400, False, None),
            ("tomate_triturado", 400, False, None),
            ("cebolla", 100, False, None),
            ("zanahoria", 100, False, None),
            ("ajo", 10, False, None),
            ("aceite_oliva", 18, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Sofríe la cebolla, la zanahoria y el ajo picados.",
            "Añade la carne y dórala; incorpora el tomate y cuece 20 minutos.",
            "Cuece la pasta y sírvela con la salsa por encima.",
        ],
    ),
    _r(
        "Salteado de tofu con verduras",
        "Tofu salteado con pimiento, calabacín y sésamo. Vegano y rico en proteína.",
        2,
        ["lunch", "dinner"],
        "asiatica",
        ["vegan", "vegetarian", "high_protein"],
        12,
        12,
        ["stovetop"],
        [
            ("tofu", 250, False, None),
            ("pimiento_rojo", 150, False, None),
            ("calabacin", 150, False, None),
            ("zanahoria", 100, False, None),
            ("sesamo", 10, False, None),
            ("aceite_girasol", 15, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Dora el tofu en dados y resérvalo.",
            "Saltea las verduras en tiras a fuego fuerte.",
            "Devuelve el tofu, añade el sésamo y saltea un minuto más.",
        ],
    ),
    _r(
        "Curry de garbanzos con leche de coco",
        "Garbanzos guisados en una salsa suave de tomate y leche de coco. Vegano.",
        4,
        ["lunch", "dinner"],
        "asiatica",
        ["vegan", "vegetarian", "high_protein", "family"],
        12,
        20,
        ["stovetop"],
        [
            ("garbanzos_cocido", 500, False, None),
            ("leche_coco", 250, False, None),
            ("tomate_triturado", 200, False, None),
            ("cebolla", 100, False, None),
            ("ajo", 10, False, None),
            ("comino", 3, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Sofríe la cebolla y el ajo con el comino.",
            "Añade el tomate y la leche de coco y lleva a ebullición suave.",
            "Incorpora los garbanzos y cuece 10 minutos.",
        ],
    ),
    # ---------- Ampliación: cenas ----------
    _r(
        "Merluza al horno con limón",
        "Lomos de merluza al horno con limón y aceite. Cena ligera y rápida de preparar.",
        2,
        ["dinner"],
        "espanola",
        ["high_protein", "low_calorie"],
        8,
        20,
        ["oven"],
        [
            ("merluza", 300, False, None),
            ("limon", 40, False, None),
            ("ajo", 8, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Coloca los lomos en una fuente de horno.",
            "Riega con aceite, zumo de limón y ajo picado.",
            "Hornea a 190 °C unos 18 minutos.",
        ],
    ),
    _r(
        "Salmón a la plancha con calabacín",
        "Salmón a la plancha acompañado de calabacín salteado. Cena rica en omega-3.",
        2,
        ["dinner"],
        "internacional",
        ["high_protein", "low_calorie"],
        8,
        12,
        ["stovetop"],
        [
            ("salmon", 300, False, None),
            ("calabacin", 200, False, None),
            ("limon", 30, False, None),
            ("aceite_oliva", 12, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Marca el salmón a la plancha por ambos lados.",
            "Saltea el calabacín en rodajas con un poco de aceite.",
            "Sirve el salmón con el calabacín y un chorrito de limón.",
        ],
    ),
    _r(
        "Crema de zanahoria al coco",
        "Crema aterciopelada de zanahoria y patata con leche de coco y comino. Vegana.",
        4,
        ["dinner"],
        "internacional",
        ["vegan", "vegetarian", "low_calorie", "family"],
        10,
        25,
        ["stovetop", "blender"],
        [
            ("zanahoria", 500, False, None),
            ("patata", 200, False, None),
            ("cebolla", 100, False, None),
            ("leche_coco", 100, False, None),
            ("comino", 2, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Sofríe la cebolla y añade la zanahoria y la patata en trozos.",
            "Cubre con agua, añade el comino y cuece hasta que estén tiernos.",
            "Tritura con la leche de coco hasta obtener una crema fina.",
        ],
    ),
    _r(
        "Revuelto de gambas y ajo",
        "Revuelto rápido de huevos con gambas y ajo. Cena exprés y muy proteica.",
        2,
        ["dinner"],
        "espanola",
        ["high_protein", "quick"],
        6,
        8,
        ["stovetop"],
        [
            ("huevos_m", 4, False, None),
            ("gambas", 150, False, None),
            ("ajo", 10, False, None),
            ("aceite_oliva", 12, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Dora el ajo laminado y añade las gambas.",
            "Incorpora los huevos batidos con sal.",
            "Remueve a fuego suave hasta que cuajen.",
        ],
    ),
    _r(
        "Sopa de verduras",
        "Sopa reconfortante de zanahoria, patata, calabacín y cebolla. Vegana y ligera.",
        4,
        ["dinner"],
        "espanola",
        ["vegan", "vegetarian", "low_calorie"],
        12,
        30,
        ["stovetop"],
        [
            ("zanahoria", 200, False, None),
            ("patata", 200, False, None),
            ("calabacin", 150, False, None),
            ("cebolla", 100, False, None),
            ("tomate", 150, False, None),
            ("aceite_oliva", 15, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Sofríe la cebolla y añade el resto de verduras troceadas.",
            "Cubre con agua y lleva a ebullición.",
            "Cuece a fuego lento 25 minutos y sazona.",
        ],
    ),
    _r(
        "Tortilla de patatas",
        "La tortilla de patatas de siempre, jugosa por dentro. Para compartir en familia.",
        4,
        ["lunch", "dinner"],
        "espanola",
        ["vegetarian", "family"],
        15,
        20,
        ["stovetop"],
        [
            ("patata", 500, False, None),
            ("huevos_l", 6, False, None),
            ("cebolla", 150, True, None),
            ("aceite_oliva", 40, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Fríe la patata en láminas con la cebolla a fuego suave.",
            "Bate los huevos con sal y mézclalos con la patata escurrida.",
            "Cuaja la tortilla por ambos lados en la sartén.",
        ],
    ),
    _r(
        "Pavo salteado con pimientos",
        "Tiras de pavo salteadas con pimiento y cebolla. Cena rápida y muy proteica.",
        2,
        ["lunch", "dinner"],
        "internacional",
        ["high_protein", "quick"],
        10,
        10,
        ["stovetop"],
        [
            ("pavo_pechuga", 300, False, None),
            ("pimiento_rojo", 150, False, None),
            ("cebolla", 100, False, None),
            ("ajo", 8, False, None),
            ("pimenton", 3, True, None),
            ("aceite_oliva", 12, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Corta el pavo en tiras y dóralo a fuego fuerte.",
            "Añade el pimiento, la cebolla y el ajo en juliana.",
            "Saltea hasta que las verduras estén tiernas y sazona.",
        ],
    ),
    _r(
        "Bacalao con tomate",
        "Bacalao guisado en salsa de tomate y pimiento. Cena tradicional de pescado.",
        2,
        ["dinner"],
        "espanola",
        ["high_protein"],
        10,
        25,
        ["stovetop"],
        [
            ("bacalao", 300, False, None),
            ("tomate_triturado", 300, False, None),
            ("pimiento_rojo", 120, False, None),
            ("cebolla", 100, False, None),
            ("ajo", 10, False, None),
            ("aceite_oliva", 18, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Sofríe la cebolla, el ajo y el pimiento.",
            "Añade el tomate y cocina la salsa 15 minutos.",
            "Incorpora el bacalao y cuece 8 minutos más.",
        ],
    ),
    _r(
        "Mejillones en salsa de tomate",
        "Mejillones guisados en una salsa de tomate y pimentón. Cena marinera con sabor.",
        2,
        ["dinner"],
        "espanola",
        ["high_protein"],
        10,
        18,
        ["stovetop"],
        [
            ("mejillones", 500, False, None),
            ("tomate_triturado", 250, False, None),
            ("cebolla", 80, False, None),
            ("ajo", 10, False, None),
            ("pimenton", 3, False, None),
            ("aceite_oliva", 12, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Sofríe la cebolla y el ajo con el pimentón.",
            "Añade el tomate y cocina la salsa 10 minutos.",
            "Incorpora los mejillones y tapa hasta que se abran.",
        ],
    ),
    _r(
        "Verduras al horno con queso",
        "Calabacín, pimiento y cebolla asados y gratinados con queso curado. Vegetariano.",
        4,
        ["lunch", "dinner"],
        "mediterranea",
        ["vegetarian", "low_calorie"],
        15,
        30,
        ["oven"],
        [
            ("calabacin", 300, False, None),
            ("pimiento_rojo", 200, False, None),
            ("cebolla", 150, False, None),
            ("tomate", 200, False, None),
            ("queso_curado", 100, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 4, False, None),
        ],
        [
            "Corta las verduras y colócalas en una bandeja con aceite y sal.",
            "Asa a 200 °C unos 25 minutos.",
            "Ralla el queso por encima y gratina hasta que se dore.",
        ],
    ),
    # ---------- Ampliación: snacks ----------
    _r(
        "Hummus de garbanzos",
        "Puré cremoso de garbanzos con sésamo, limón y ajo. Vegano para untar.",
        4,
        ["snack"],
        "arabe",
        ["vegan", "vegetarian", "high_protein"],
        10,
        0,
        ["blender"],
        [
            ("garbanzos_cocido", 400, False, None),
            ("sesamo", 30, False, None),
            ("limon", 40, False, None),
            ("ajo", 8, False, None),
            ("comino", 2, False, None),
            ("aceite_oliva", 20, False, None),
            ("sal", 3, False, None),
        ],
        [
            "Tritura los garbanzos con el sésamo, el limón y el ajo.",
            "Añade el comino, el aceite y la sal.",
            "Bate hasta lograr una crema fina y sirve con un hilo de aceite.",
        ],
    ),
    _r(
        "Tostada de queso fresco y tomate",
        "Tostada de pan con queso fresco y rodajas de tomate. Merienda rápida.",
        2,
        ["snack", "breakfast"],
        "mediterranea",
        ["vegetarian", "quick"],
        5,
        3,
        ["toaster"],
        [
            ("pan_molde", 100, False, None),
            ("queso_fresco", 120, False, None),
            ("tomate", 120, False, None),
            ("aceite_oliva", 8, True, None),
            ("sal", 2, True, None),
        ],
        [
            "Tuesta el pan de molde.",
            "Unta el queso fresco y coloca rodajas de tomate.",
            "Aliña con un hilo de aceite y sal.",
        ],
    ),
    _r(
        "Manzana con almendras",
        "Manzana en gajos con un puñado de almendras. Tentempié vegano y crujiente.",
        1,
        ["snack"],
        "internacional",
        ["vegan", "vegetarian", "quick"],
        3,
        0,
        [],
        [
            ("manzana", 150, False, None),
            ("almendra", 30, False, None),
        ],
        [
            "Corta la manzana en gajos.",
            "Acompaña con las almendras.",
        ],
    ),
    _r(
        "Yogur con fresas",
        "Yogur natural con fresas troceadas. Merienda fresca y baja en calorías.",
        2,
        ["snack"],
        "internacional",
        ["vegetarian", "quick", "low_calorie"],
        4,
        0,
        [],
        [
            ("yogur_natural", 250, False, None),
            ("fresa", 150, False, None),
            ("miel", 10, True, None),
        ],
        [
            "Reparte el yogur en dos boles.",
            "Añade las fresas troceadas.",
            "Endulza con miel si se desea.",
        ],
    ),
    _r(
        "Tortilla francesa",
        "Sencilla tortilla francesa de dos huevos. Merienda o cena exprés y proteica.",
        1,
        ["snack", "breakfast", "dinner"],
        "espanola",
        ["vegetarian", "high_protein", "quick"],
        3,
        5,
        ["stovetop"],
        [
            ("huevos_m", 2, False, None),
            ("aceite_oliva", 8, False, None),
            ("sal", 2, False, None),
        ],
        [
            "Bate los huevos con sal.",
            "Cuájalos en la sartén con un poco de aceite.",
            "Enrolla la tortilla y sirve.",
        ],
    ),
    _r(
        "Guacamole con pan",
        "Guacamole de aguacate, tomate y cebolla con pan tostado. Vegano para picar.",
        2,
        ["snack"],
        "internacional",
        ["vegan", "vegetarian", "quick"],
        10,
        3,
        ["toaster"],
        [
            ("aguacate", 200, False, None),
            ("tomate", 100, False, None),
            ("cebolla", 50, False, None),
            ("limon", 30, False, None),
            ("pan_integral", 100, False, None),
            ("sal", 2, False, None),
        ],
        [
            "Machaca el aguacate con el zumo de limón y la sal.",
            "Mezcla con el tomate y la cebolla picados.",
            "Sirve con el pan tostado.",
        ],
    ),
    _r(
        "Batido de fresa y yogur",
        "Batido cremoso de fresa y yogur natural. Merienda ligera y refrescante.",
        2,
        ["snack"],
        "internacional",
        ["vegetarian", "quick", "low_calorie"],
        5,
        0,
        ["blender"],
        [
            ("fresa", 200, False, None),
            ("yogur_natural", 200, False, None),
            ("leche_desnatada", 100, False, None),
            ("miel", 10, True, None),
        ],
        [
            "Pon la fresa, el yogur y la leche en la batidora.",
            "Tritura hasta que quede cremoso.",
            "Endulza con miel al gusto.",
        ],
    ),
    _r(
        "Tostada de atún y tomate",
        "Tostada de pan con atún y tomate. Merienda salada rápida y proteica.",
        2,
        ["snack"],
        "mediterranea",
        ["high_protein", "quick"],
        6,
        3,
        ["toaster"],
        [
            ("pan_integral", 100, False, None),
            ("atun_lata", 120, False, None),
            ("tomate", 120, False, None),
            ("aceite_oliva", 8, True, None),
        ],
        [
            "Tuesta el pan.",
            "Reparte el atún escurrido y el tomate en rodajas.",
            "Riega con un hilo de aceite.",
        ],
    ),
    _r(
        "Mix de frutos secos",
        "Puñado variado de almendras, nueces, anacardos y cacahuetes. Vegano y energético.",
        2,
        ["snack"],
        "internacional",
        ["vegan", "vegetarian", "quick"],
        3,
        0,
        [],
        [
            ("almendra", 25, False, None),
            ("nuez", 25, False, None),
            ("anacardo", 25, False, None),
            ("cacahuete", 25, False, None),
        ],
        [
            "Mezcla los frutos secos en un bol.",
            "Reparte en dos raciones.",
        ],
    ),
    _r(
        "Queso curado con nueces",
        "Tacos de queso curado con nueces. Aperitivo sencillo y saciante.",
        2,
        ["snack"],
        "espanola",
        ["vegetarian", "quick"],
        4,
        0,
        [],
        [
            ("queso_curado", 100, False, None),
            ("nuez", 40, False, None),
        ],
        [
            "Corta el queso en tacos.",
            "Sirve con las nueces.",
        ],
    ),
    _r(
        "Naranja y anacardos",
        "Gajos de naranja con anacardos. Merienda vegana rápida y vitaminada.",
        1,
        ["snack"],
        "internacional",
        ["vegan", "vegetarian", "quick", "low_calorie"],
        4,
        0,
        [],
        [
            ("naranja", 200, False, None),
            ("anacardo", 30, False, None),
        ],
        [
            "Pela y separa los gajos de naranja.",
            "Acompaña con los anacardos.",
        ],
    ),
    _r(
        "Quesadilla de queso",
        "Tortilla de trigo rellena de queso curado fundido. Merienda caliente y rápida.",
        2,
        ["snack"],
        "internacional",
        ["vegetarian", "quick"],
        5,
        6,
        ["stovetop"],
        [
            ("tortillas_trigo", 120, False, None),
            ("queso_curado", 100, False, None),
            ("aceite_girasol", 6, True, None),
        ],
        [
            "Reparte el queso sobre media tortilla y dóblala.",
            "Dórala en la sartén por ambos lados hasta que el queso funda.",
            "Corta en triángulos y sirve.",
        ],
    ),
]
