"""Build-provenance document generator (feat immutable-build-provenance).

Produces a canonical, versioned JSON document describing the runtime bundle that built an image.
It is generated BYTE-IDENTICALLY for the API and worker builds of the same commit, because both
are built from one image (``apps/api/Dockerfile``) and the manifests are computed over the same
base-relative layout (``/app`` in the image == ``apps/api`` in the repo).

Hash contract (documented exactly):
- ``source_tree_hash``   : every runtime file — ``src`` (all packages), ``migrations``,
                           ``pyproject.toml``, ``uv.lock``.
- ``api_artifact_hash``  : ``src/cestaplan_api`` (models, services, remediation tools),
                           ``src/cestaplan_engine`` (shared), ``migrations``, ``alembic.ini``,
                           ``pyproject.toml``, ``uv.lock``.
- ``worker_artifact_hash``: ``src/cestaplan_api`` (shared), ``src/cestaplan_engine`` (shared),
                           ``src/cestaplan_worker``, ``pyproject.toml``, ``uv.lock``.

``cestaplan_api`` and ``cestaplan_engine`` are shared (imported by both api and worker), so a change
there moves BOTH artifact hashes; ``migrations``/``alembic.ini`` move only the API hash;
``cestaplan_worker`` moves only the worker hash.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from cestaplan_api.provenance.manifest import ProvenanceError, build_manifest, manifest_hash

# schema_version 3 added the pinned PostgreSQL 18 CLIENT identity (package + version + measured
# pg_restore/pg_dump binary sha256s). schema_version 4 adds the FULL runtime dependency/library
# closure (postgresql_runtime_dependencies + postgresql_runtime_files + postgresql_runtime_manifest_
# hash), measured in-image, so the document cannot stay the same when any shipped library, package
# version or file sha changes — the runtime VerifiedPgRestore re-verifies the closure against it.
EVIDENCE_DOCUMENT_SCHEMA_VERSION = 4
GENERATOR_VERSION = "build-provenance-v1"

# --- Pinned PostgreSQL 18 client (MUST match apps/api/Dockerfile; measured at build) ----
POSTGRESQL_CLIENT_PACKAGE = "postgresql-client-18"
PG_CLIENT_MAJOR = "18"
PG_CLIENT_BIN_DIR = "/usr/lib/postgresql/18/bin"
PG_CLIENT_BINARIES = ("pg_restore", "pg_dump")
# The build target is amd64; arch-independent packages (e.g. postgresql-client-common) are "all".
_PG_ARCH = "amd64"
_PG_ARCH_ALLOWED = frozenset({"amd64", "all"})
# Purely-virtual kernel objects have no backing file/package — the ONLY allowlisted ldd entries.
_PG_VDSO_ALLOWLIST = frozenset({"linux-vdso.so.1", "linux-gate.so.1"})
_PG_PKG_VERSION_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9.+~:-]{0,80}$")
_ABS_PATH_RE = re.compile(r"^/[^\x00]*$")

# --- Pinned toolchain (MUST match apps/api/Dockerfile exactly; CI asserts equality) ---------------
TOOLCHAIN_CONTRACT_VERSION = "toolchain-v1"
PYTHON_BASE_IMAGE = "python:3.12-slim"
PYTHON_BASE_IMAGE_DIGEST = \
    "sha256:57cd7c3a7a273101a6485ba99423ee568157882804b1124b4dd04266317710de"
UV_IMAGE = "ghcr.io/astral-sh/uv:0.9.8"
UV_IMAGE_DIGEST = "sha256:08f409e1d53e77dfb5b65c788491f8ca70fe1d2d459f41c89afa2fcbef998abe"

TRUST_ROOT_FILENAME = "authorization-trust-root.json"
# Fixed, baked path — never substituted by a runtime env var in production.
BUILD_AUTHORIZATION_TRUST_ROOT_PATH = "/app/authorization-trust-root.json"

# The committed APT lock — a build input: COPYed to /app, consumed by verify_lock at build time and
# part of the immutable runtime bundle. Measured in every scope so ANY byte change moves all three
# provenance hashes.
PG_RUNTIME_LOCK_FILENAME = "postgresql-client-18-runtime.lock.json"

# Build-affecting, runtime-relevant files hashed in EVERY scope (Dockerfile + trust-root move all
# three hashes, so a toolchain or trust-root change can never leave the hashes unchanged). README.md
# is a BUILD INPUT — pyproject's `readme` points at it and it is COPYed before `uv sync`, so it can
# affect the installed package; it is measured in every scope so a README change moves all three
# hashes (§4v4). The pg runtime lock is likewise a build input, covered in every scope.
_BUILD_FILES = ["Dockerfile", TRUST_ROOT_FILENAME, "README.md", PG_RUNTIME_LOCK_FILENAME]
SOURCE_TREE_INCLUDES = ["src", "migrations", "alembic.ini", "pyproject.toml", "uv.lock",
                        *_BUILD_FILES]
API_ARTIFACT_INCLUDES = ["src/cestaplan_api", "src/cestaplan_engine", "migrations", "alembic.ini",
                         "pyproject.toml", "uv.lock", *_BUILD_FILES]
WORKER_ARTIFACT_INCLUDES = ["src/cestaplan_api", "src/cestaplan_engine", "src/cestaplan_worker",
                            "pyproject.toml", "uv.lock", *_BUILD_FILES]

_COMMIT_RE = re.compile(r"^[0-9a-f]{40}$")
_REVISION_RE = re.compile(r"^[0-9a-z_]{6,64}$")
_DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_PG_PKGVER_RE = re.compile(r"^18\.[0-9A-Za-z.+~:-]{1,60}$")  # e.g. 18.4-1.pgdg13+1
_PG_VER_RE = re.compile(r"^18\.[0-9]+$")                     # normalized major.minor, e.g. 18.4


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(1 << 20):
            h.update(chunk)
    return h.hexdigest()


def measure_pg_client(bin_dir: str | Path = PG_CLIENT_BIN_DIR) -> dict[str, str]:
    """Measure the ACTUAL installed PostgreSQL 18 client (build time, inside the image): the binary
    sha256s of pg_restore/pg_dump, their normalized versions and the exact dpkg package version.
    Fail-closed (ProvenanceError) if a binary is missing, the major is not 18, or the package is
    unknown — the values are read from the artifact, never invented."""
    d = Path(bin_dir)
    pr, pd = d / "pg_restore", d / "pg_dump"
    if not pr.is_file() or not pd.is_file():
        raise ProvenanceError("pg_client_missing", "")

    def _ver(exe: Path) -> tuple[str, str]:
        r = subprocess.run([str(exe), "--version"], capture_output=True, text=True,
                           errors="replace", timeout=30, check=False)
        if r.returncode != 0:
            raise ProvenanceError("pg_client_version_failed", "")
        m = re.search(r"\(PostgreSQL\)\s+(\d+)\.(\d+)", r.stdout)
        if not m:
            raise ProvenanceError("pg_client_version_unparsed", "")
        return m.group(1), f"{m.group(1)}.{m.group(2)}"

    pr_major, pr_ver = _ver(pr)
    pd_major, _pd_ver = _ver(pd)
    if pr_major != PG_CLIENT_MAJOR or pd_major != PG_CLIENT_MAJOR:
        raise ProvenanceError("pg_client_major_mismatch", "")
    dq = subprocess.run(["dpkg-query", "-W", "-f=${Version}", POSTGRESQL_CLIENT_PACKAGE],
                        capture_output=True, text=True, errors="replace", timeout=30, check=False)
    if dq.returncode != 0 or not dq.stdout.strip():
        raise ProvenanceError("pg_client_package_unknown", "")
    return {
        "postgresql_client_package": POSTGRESQL_CLIENT_PACKAGE,
        "postgresql_client_package_version": dq.stdout.strip(),
        "pg_restore_major": pr_major,
        "pg_restore_version": pr_ver,
        "pg_restore_binary_sha256": _sha256_file(pr),
        "pg_dump_binary_sha256": _sha256_file(pd),
    }


def _validate_pg_client(pg: Any) -> dict[str, str]:
    if not isinstance(pg, dict):
        raise ProvenanceError("pg_client_invalid", "")
    if pg.get("postgresql_client_package") != POSTGRESQL_CLIENT_PACKAGE:
        raise ProvenanceError("pg_client_package_invalid", "")
    if not _PG_PKGVER_RE.match(str(pg.get("postgresql_client_package_version", ""))):
        raise ProvenanceError("pg_client_package_version_invalid", "")
    if pg.get("pg_restore_major") != PG_CLIENT_MAJOR:
        raise ProvenanceError("pg_restore_major_invalid", "")
    if not _PG_VER_RE.match(str(pg.get("pg_restore_version", ""))):
        raise ProvenanceError("pg_restore_version_invalid", "")
    for f in ("pg_restore_binary_sha256", "pg_dump_binary_sha256"):
        if not _SHA256_RE.match(str(pg.get(f, ""))):
            raise ProvenanceError(f"{f}_invalid", "")
    return {k: pg[k] for k in (
        "postgresql_client_package", "postgresql_client_package_version", "pg_restore_major",
        "pg_restore_version", "pg_restore_binary_sha256", "pg_dump_binary_sha256")}


def _pg_run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, capture_output=True, text=True, errors="replace", timeout=60,
                          check=False)


def _pg_dpkg_owner(path: str) -> str:
    """The Debian package that OWNS an on-disk file, via ``dpkg -S`` (fail-closed if unowned)."""
    r = _pg_run(["dpkg-query", "-S", path])
    if r.returncode != 0 or not r.stdout.strip():
        raise ProvenanceError("pg_runtime_file_unowned", "")
    # Lines look like "pkg[:arch][, pkg2]: /abs/path"; pick the one whose path matches exactly.
    for line in r.stdout.splitlines():
        pkgs, sep, p = line.rpartition(": ")
        if sep and p.strip() == path:
            return pkgs.split(",")[0].strip().split(":")[0]
    raise ProvenanceError("pg_runtime_file_unowned", "")


def _pg_pkg_version_arch(pkg: str) -> tuple[str, str]:
    r = _pg_run(["dpkg-query", "-W", "-f=${Version}\t${Architecture}", pkg])
    parts = r.stdout.split("\t")
    if r.returncode != 0 or len(parts) != 2 or not parts[0].strip() or not parts[1].strip():
        raise ProvenanceError("pg_runtime_pkg_unknown", "")
    return parts[0].strip(), parts[1].strip()


def _pg_ldd_paths(binary: str) -> list[str]:
    """Absolute paths of the shared objects ``binary`` actually resolves to (fail-closed on any
    'not found' or unexpected line). Purely-virtual kernel objects (linux-vdso) are skipped."""
    r = _pg_run(["ldd", binary])
    if r.returncode != 0:
        raise ProvenanceError("pg_runtime_ldd_failed", "")
    out: list[str] = []
    for raw in r.stdout.splitlines():
        line = raw.strip()
        if not line:
            continue
        name = line.split()[0]
        if name in _PG_VDSO_ALLOWLIST or name.startswith("linux-vdso"):
            continue
        if "=>" in line:
            rhs = line.split("=>", 1)[1].strip()
            if rhs.startswith("not found"):
                raise ProvenanceError("pg_runtime_lib_unresolved", "")
            path = rhs.split(" (")[0].strip()
            if not path and name.startswith("/"):
                path = name  # "name => (0x..)": the soname is itself an absolute path
        elif name.startswith("/"):
            path = name  # e.g. the dynamic loader: "/lib64/ld-linux-x86-64.so.2 (0x..)"
        else:
            raise ProvenanceError("pg_runtime_ldd_unparsed", "")
        if not path.startswith("/"):
            raise ProvenanceError("pg_runtime_lib_unresolved", "")
        out.append(path)
    return out


def measure_pg_runtime(bin_dir: str | Path = PG_CLIENT_BIN_DIR) -> dict[str, Any]:
    """Measure the FULL runtime closure of the pinned pg_restore/pg_dump (build time, in the image):
    every shared object they resolve to, the Debian package that owns each file, its exact version +
    architecture, and the sha256 of each RESOLVED (symlink-free) regular file. Fail-closed on any
    unresolved ldd entry, unowned file, unknown package or unexpected architecture. Deterministic
    (sorted, de-duplicated) so two generations in the same image produce identical bytes."""
    d = Path(bin_dir)
    resolved: set[str] = set()
    for name in PG_CLIENT_BINARIES:
        b = d / name
        if not b.is_file():
            raise ProvenanceError("pg_client_missing", "")
        resolved.add(str(Path(str(b)).resolve()))
        for lib in _pg_ldd_paths(str(b)):
            resolved.add(str(Path(lib).resolve()))
    files: list[dict[str, str]] = []
    pkgs: dict[str, tuple[str, str]] = {}
    for rp in sorted(resolved):
        p = Path(rp)
        if p.is_symlink() or not p.is_file():
            raise ProvenanceError("pg_runtime_file_irregular", "")
        pkg = _pg_dpkg_owner(rp)
        version, arch = _pg_pkg_version_arch(pkg)
        if arch not in _PG_ARCH_ALLOWED:
            raise ProvenanceError("pg_runtime_arch_unexpected", "")
        pkgs[pkg] = (version, arch)
        files.append({"package": pkg, "path": rp, "sha256": _sha256_file(p)})
    deps = [{"architecture": a, "package": pkg, "version": v}
            for pkg, (v, a) in sorted(pkgs.items())]
    files.sort(key=lambda e: (e["path"], e["package"]))
    core = {"postgresql_runtime_dependencies": deps, "postgresql_runtime_files": files}
    return {**core, "postgresql_runtime_manifest_hash": _pg_runtime_manifest_hash(core)}


def _pg_runtime_manifest_hash(core: Mapping[str, Any]) -> str:
    """Canonical sha256 over the ordered dependency + file manifest (a sub-hash the loader
    recomputes, so a mutated version/library/sha is detected independently of the document hash)."""
    payload = {"postgresql_runtime_dependencies": core["postgresql_runtime_dependencies"],
               "postgresql_runtime_files": core["postgresql_runtime_files"]}
    return hashlib.sha256((canonical_json(payload) + "\n").encode()).hexdigest()


def _validate_pg_runtime(doc: Any) -> dict[str, Any]:
    """Strict validation of the runtime manifest fields (schema 4). Rejects a missing field, a
    non-list, an unordered or duplicated entry, a missing version, an unexpected architecture, an
    invalid sha, a relative path, an uncovered binary, or a wrong manifest hash. Returns the exact
    three fields on success."""
    if not isinstance(doc, dict):
        raise ProvenanceError("pg_runtime_invalid", "")
    deps = doc.get("postgresql_runtime_dependencies")
    files = doc.get("postgresql_runtime_files")
    mhash = doc.get("postgresql_runtime_manifest_hash")
    if not isinstance(deps, list) or not deps or not isinstance(files, list) or not files:
        raise ProvenanceError("pg_runtime_manifest_missing", "")
    dep_keys = []
    for dep in deps:
        if (not isinstance(dep, dict) or set(dep) != {"architecture", "package", "version"}):
            raise ProvenanceError("pg_runtime_dependency_malformed", "")
        if dep["architecture"] not in _PG_ARCH_ALLOWED:
            raise ProvenanceError("pg_runtime_arch_unexpected", "")
        if not isinstance(dep["package"], str) or not dep["package"]:
            raise ProvenanceError("pg_runtime_dependency_malformed", "")
        if not _PG_PKG_VERSION_RE.match(str(dep["version"])):
            raise ProvenanceError("pg_runtime_version_invalid", "")
        dep_keys.append(dep["package"])
    if dep_keys != sorted(dep_keys) or len(dep_keys) != len(set(dep_keys)):
        raise ProvenanceError("pg_runtime_dependencies_unordered", "")
    dep_pkgs = set(dep_keys)
    file_keys = []
    covered_paths = set()
    for fe in files:
        if not isinstance(fe, dict) or set(fe) != {"package", "path", "sha256"}:
            raise ProvenanceError("pg_runtime_file_malformed", "")
        if not isinstance(fe["path"], str) or not _ABS_PATH_RE.match(fe["path"]):
            raise ProvenanceError("pg_runtime_path_invalid", "")
        if not _SHA256_RE.match(str(fe["sha256"])):
            raise ProvenanceError("pg_runtime_sha_invalid", "")
        if fe["package"] not in dep_pkgs:  # every file's owner must be a declared dependency
            raise ProvenanceError("pg_runtime_file_uncovered", "")
        file_keys.append((fe["path"], fe["package"]))
        covered_paths.add(fe["path"])
    if file_keys != sorted(file_keys) or len(file_keys) != len(set(file_keys)):
        raise ProvenanceError("pg_runtime_files_unordered", "")
    # Both pinned binaries must be covered by the file manifest.
    for name in PG_CLIENT_BINARIES:
        if f"{PG_CLIENT_BIN_DIR}/{name}" not in covered_paths:
            raise ProvenanceError("pg_runtime_binary_uncovered", "")
    core = {"postgresql_runtime_dependencies": deps, "postgresql_runtime_files": files}
    if not _SHA256_RE.match(str(mhash)) or _pg_runtime_manifest_hash(core) != mhash:
        raise ProvenanceError("pg_runtime_manifest_hash_mismatch", "")
    return {"postgresql_runtime_dependencies": deps, "postgresql_runtime_files": files,
            "postgresql_runtime_manifest_hash": mhash}


# dependency_closure_hash is computed EXCLUSIVELY over these four (unchanged); the full byte
# identity of the lock is bound separately via the three provenance scope hashes (_BUILD_FILES).
_LOCK_CORE_FIELDS = ("architecture", "codename", "distribution", "packages")
# The lock is a REVIEWED constant: exact field set, platform, source and schema are pinned.
_LOCK_ALLOWED_FIELDS = frozenset({
    "_comment", "schema_version", "distribution", "codename", "architecture", "source", "packages",
    "dependency_closure_hash"})
_LOCK_SCHEMA_VERSION = 1
_LOCK_DISTRIBUTION = "debian"
_LOCK_CODENAME = "trixie"
_LOCK_ARCHITECTURE = "amd64"
_LOCK_SOURCE = "https://apt.postgresql.org/pub/repos/apt trixie-pgdg main"


def _pg_lock_closure_hash(lock: Mapping[str, Any]) -> str:
    core = {k: lock[k] for k in _LOCK_CORE_FIELDS}
    return hashlib.sha256((canonical_json(core) + "\n").encode()).hexdigest()


def _lock_no_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    keys = [k for k, _ in pairs]
    if len(keys) != len(set(keys)):
        raise ProvenanceError("pg_lock_duplicate_key", "")
    return dict(pairs)


def _lock_reject_constant(const: str) -> Any:
    raise ProvenanceError("pg_lock_non_finite", const)  # NaN / Infinity / -Infinity


def load_pg_runtime_lock(path: str | Path) -> dict[str, Any]:
    """Load + strictly self-verify the committed APT lock (fail-closed). The lock pins the
    PGDG-sourced closure (postgresql-client-18/libpq5/postgresql-client-common) so APT cannot
    silently install a different set; the base-image libraries are pinned by the base image digest
    and captured in the runtime file manifest instead. The lock is a REVIEWED constant: the exact
    field set, platform, source, schema and (canonical, ordered, de-duplicated) package contract are
    enforced, duplicate JSON keys and NaN/Infinity are rejected, and dependency_closure_hash must be
    correct."""
    try:
        raw = Path(path).read_bytes()
    except OSError as exc:
        raise ProvenanceError("pg_lock_unreadable", "") from exc
    try:
        lock = json.loads(raw, object_pairs_hook=_lock_no_duplicate_keys,
                          parse_constant=_lock_reject_constant)
    except json.JSONDecodeError as exc:
        raise ProvenanceError("pg_lock_invalid", "") from exc
    if not isinstance(lock, dict):
        raise ProvenanceError("pg_lock_invalid", "")
    if set(lock) != _LOCK_ALLOWED_FIELDS:  # no unknown field, no missing field
        raise ProvenanceError("pg_lock_fields_mismatch", "")
    if lock["schema_version"] != _LOCK_SCHEMA_VERSION or isinstance(lock["schema_version"], bool):
        raise ProvenanceError("pg_lock_schema_unsupported", "")
    if (lock["distribution"] != _LOCK_DISTRIBUTION or lock["codename"] != _LOCK_CODENAME
            or lock["architecture"] != _LOCK_ARCHITECTURE):
        raise ProvenanceError("pg_lock_platform_invalid", "")
    if lock["source"] != _LOCK_SOURCE:
        raise ProvenanceError("pg_lock_source_invalid", "")
    if not isinstance(lock["_comment"], str) or not lock["_comment"].strip():
        raise ProvenanceError("pg_lock_comment_invalid", "")
    if not isinstance(lock["packages"], list) or not lock["packages"]:
        raise ProvenanceError("pg_lock_packages_invalid", "")
    for pkg in lock["packages"]:
        if (not isinstance(pkg, dict) or set(pkg) != {"package", "version"}
                or not isinstance(pkg["package"], str) or not pkg["package"]
                or not _PG_PKG_VERSION_RE.match(str(pkg["version"]))):
            raise ProvenanceError("pg_lock_package_malformed", "")
    names = [p["package"] for p in lock["packages"]]
    if names != sorted(names) or len(names) != len(set(names)):
        raise ProvenanceError("pg_lock_packages_unordered", "")
    if _pg_lock_closure_hash(lock) != lock["dependency_closure_hash"]:
        raise ProvenanceError("pg_lock_hash_mismatch", "")
    return lock


def _read_os_release(path: str | Path = "/etc/os-release") -> tuple[str, str]:
    fields: dict[str, str] = {}
    for line in Path(path).read_text().splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            k, _, v = line.partition("=")
            fields[k.strip()] = v.strip().strip('"')
    return fields.get("ID", ""), fields.get("VERSION_CODENAME", "")


def verify_pg_runtime_lock(lock: Mapping[str, Any], *, distribution: str, codename: str,
                           architecture: str) -> None:
    """Fail-closed comparison of the INSTALLED closure against the committed lock (build time). Each
    locked package's dpkg-recorded version must match EXACTLY; the platform must match; no fallback,
    no automatic regeneration."""
    if (lock["distribution"] != distribution or lock["codename"] != codename
            or lock["architecture"] != architecture):
        raise ProvenanceError("pg_lock_platform_mismatch", "")
    for pkg in lock["packages"]:
        installed, _arch = _pg_pkg_version_arch(pkg["package"])
        if installed != pkg["version"]:
            raise ProvenanceError("pg_lock_version_mismatch", pkg["package"])


def resolve_commit_sha(sources: Mapping[str, str | None]) -> str:
    """Resolve the build commit from BUILD_COMMIT_SHA / RAILWAY_GIT_COMMIT_SHA / APP_COMMIT_SHA in
    that priority order (v2/§5). Every present value must be 40-hex; if two are present and DIFFER
    the build fails — a silent pick between contradictory values is never allowed."""
    present = {name: v.strip() for name, v in sources.items() if isinstance(v, str) and v.strip()}
    for name, v in present.items():
        if not _COMMIT_RE.match(v):
            raise ProvenanceError("commit_sha_invalid", name)
    distinct = set(present.values())
    if len(distinct) > 1:
        raise ProvenanceError("commit_sha_conflict", ",".join(sorted(present)))
    for name in ("BUILD_COMMIT_SHA", "RAILWAY_GIT_COMMIT_SHA", "APP_COMMIT_SHA"):
        if name in present:
            return present[name]
    raise ProvenanceError("commit_sha_missing", "")


def canonical_json(obj: Any) -> str:
    """Canonical JSON: sorted keys, no whitespace, stable unicode, stable nulls."""
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def detect_alembic_head(migrations_dir: str | Path) -> str:
    """Resolve the single Alembic head from the migration scripts alone (no DB). Fail-closed when
    there is not exactly one head."""
    versions = Path(migrations_dir) / "versions"
    if not versions.is_dir():
        raise ProvenanceError("migrations_versions_missing", "")
    revisions: set[str] = set()
    down: set[str] = set()
    for py in sorted(versions.glob("*.py")):
        text = py.read_text()
        rev = re.search(r"^revision(?:\s*:\s*[^=]+)?\s*=\s*['\"]([0-9a-z_]+)['\"]", text, re.M)
        dwn = re.search(r"^down_revision(?:\s*:\s*[^=]+)?\s*=\s*['\"]([0-9a-z_]+)['\"]", text, re.M)
        if rev:
            revisions.add(rev.group(1))
        if dwn:
            down.add(dwn.group(1))
    heads = revisions - down
    if len(heads) != 1:
        raise ProvenanceError("alembic_head_not_unique", str(sorted(heads)))
    return next(iter(heads))


def generate_provenance_document(base: str | Path, commit_sha: str, alembic_revision: str,
                                 pg_client: dict[str, str],
                                 pg_runtime: dict[str, Any]) -> dict[str, Any]:
    """Build the canonical provenance document (schema_version 4). Fail-closed on a missing/invalid
    commit, revision, toolchain digest, PostgreSQL client identity or runtime dependency manifest.
    Contains NO timestamps or non-reproducible metadata; the toolchain digests come from reviewed
    constants while the pg-client fields AND the full runtime dependency/library manifest are
    MEASURED from the installed image (``measure_pg_client`` + ``measure_pg_runtime``) — both baked
    identically into the API and worker images."""
    if not isinstance(commit_sha, str) or not _COMMIT_RE.match(commit_sha):
        raise ProvenanceError("commit_sha_invalid", "")
    if not isinstance(alembic_revision, str) or not _REVISION_RE.match(alembic_revision):
        raise ProvenanceError("alembic_revision_invalid", "")
    for digest in (PYTHON_BASE_IMAGE_DIGEST, UV_IMAGE_DIGEST):
        if not _DIGEST_RE.match(digest):
            raise ProvenanceError("toolchain_digest_invalid", "")
    pg = _validate_pg_client(pg_client)
    runtime = _validate_pg_runtime(pg_runtime)
    from cestaplan_api.provenance.trust_root import trust_root_hash
    trust_hash = trust_root_hash(Path(base) / TRUST_ROOT_FILENAME)
    src = manifest_hash(build_manifest(base, SOURCE_TREE_INCLUDES))
    api = manifest_hash(build_manifest(base, API_ARTIFACT_INCLUDES))
    worker = manifest_hash(build_manifest(base, WORKER_ARTIFACT_INCLUDES))
    return {
        "schema_version": EVIDENCE_DOCUMENT_SCHEMA_VERSION,
        "commit_sha": commit_sha,
        "source_tree_hash": src,
        "api_artifact_hash": api,
        "worker_artifact_hash": worker,
        "alembic_revision": alembic_revision,
        "generator_version": GENERATOR_VERSION,
        "toolchain_contract_version": TOOLCHAIN_CONTRACT_VERSION,
        "python_base_image_digest": PYTHON_BASE_IMAGE_DIGEST,
        "uv_image_digest": UV_IMAGE_DIGEST,
        "authorization_trust_root_hash": trust_hash,
        **pg,
        **runtime,
    }


def render_document(document: dict[str, Any]) -> bytes:
    """The exact bytes written to ``build-provenance.json`` — canonical JSON + a trailing newline,
    identical across the API and worker builds."""
    return (canonical_json(document) + "\n").encode()


def document_sha256(document: dict[str, Any]) -> str:
    return hashlib.sha256(render_document(document)).hexdigest()
