"""Build-provenance document generator (feat immutable-build-provenance).

Produces a canonical, versioned JSON document describing the runtime bundle that built an image.
It is generated BYTE-IDENTICALLY for the API and worker builds of the same commit, because both
are built from one image (``apps/api/Dockerfile``) and the manifests are computed over the same
base-relative layout (``/app`` in the image == ``apps/api`` in the repo).

Hash contract (documented exactly):
- ``source_tree_hash``   : every runtime file — ``src`` (all packages), ``migrations``,
                           ``pyproject.toml``, ``uv.lock``.
- ``api_artifact_hash``  : ``src/cestaplan_api`` (models, services, remediation tools),
                           ``src/cestaplan_engine`` (shared), ``migrations``, ``alembic.ini``,
                           ``pyproject.toml``, ``uv.lock``.
- ``worker_artifact_hash``: ``src/cestaplan_api`` (shared), ``src/cestaplan_engine`` (shared),
                           ``src/cestaplan_worker``, ``pyproject.toml``, ``uv.lock``.

``cestaplan_api`` and ``cestaplan_engine`` are shared (imported by both api and worker), so a change
there moves BOTH artifact hashes; ``migrations``/``alembic.ini`` move only the API hash;
``cestaplan_worker`` moves only the worker hash.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

from cestaplan_api.provenance.manifest import ProvenanceError, build_manifest, manifest_hash

EVIDENCE_DOCUMENT_SCHEMA_VERSION = 1
GENERATOR_VERSION = "build-provenance-v1"

SOURCE_TREE_INCLUDES = ["src", "migrations", "alembic.ini", "pyproject.toml", "uv.lock"]
API_ARTIFACT_INCLUDES = ["src/cestaplan_api", "src/cestaplan_engine", "migrations", "alembic.ini",
                         "pyproject.toml", "uv.lock"]
WORKER_ARTIFACT_INCLUDES = ["src/cestaplan_api", "src/cestaplan_engine", "src/cestaplan_worker",
                            "pyproject.toml", "uv.lock"]

_COMMIT_RE = re.compile(r"^[0-9a-f]{40}$")
_REVISION_RE = re.compile(r"^[0-9a-z_]{6,64}$")


def canonical_json(obj: Any) -> str:
    """Canonical JSON: sorted keys, no whitespace, stable unicode, stable nulls."""
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def detect_alembic_head(migrations_dir: str | Path) -> str:
    """Resolve the single Alembic head from the migration scripts alone (no DB). Fail-closed when
    there is not exactly one head."""
    versions = Path(migrations_dir) / "versions"
    if not versions.is_dir():
        raise ProvenanceError("migrations_versions_missing", "")
    revisions: set[str] = set()
    down: set[str] = set()
    for py in sorted(versions.glob("*.py")):
        text = py.read_text()
        rev = re.search(r"^revision(?:\s*:\s*[^=]+)?\s*=\s*['\"]([0-9a-z_]+)['\"]", text, re.M)
        dwn = re.search(r"^down_revision(?:\s*:\s*[^=]+)?\s*=\s*['\"]([0-9a-z_]+)['\"]", text, re.M)
        if rev:
            revisions.add(rev.group(1))
        if dwn:
            down.add(dwn.group(1))
    heads = revisions - down
    if len(heads) != 1:
        raise ProvenanceError("alembic_head_not_unique", str(sorted(heads)))
    return next(iter(heads))


def generate_provenance_document(base: str | Path, commit_sha: str,
                                 alembic_revision: str) -> dict[str, Any]:
    """Build the canonical provenance document. Fail-closed on a missing/invalid commit or revision.
    Contains NO timestamps or non-reproducible metadata."""
    if not isinstance(commit_sha, str) or not _COMMIT_RE.match(commit_sha):
        raise ProvenanceError("commit_sha_invalid", "")
    if not isinstance(alembic_revision, str) or not _REVISION_RE.match(alembic_revision):
        raise ProvenanceError("alembic_revision_invalid", "")
    src = manifest_hash(build_manifest(base, SOURCE_TREE_INCLUDES))
    api = manifest_hash(build_manifest(base, API_ARTIFACT_INCLUDES))
    worker = manifest_hash(build_manifest(base, WORKER_ARTIFACT_INCLUDES))
    return {
        "schema_version": EVIDENCE_DOCUMENT_SCHEMA_VERSION,
        "commit_sha": commit_sha,
        "source_tree_hash": src,
        "api_artifact_hash": api,
        "worker_artifact_hash": worker,
        "alembic_revision": alembic_revision,
        "generator_version": GENERATOR_VERSION,
    }


def render_document(document: dict[str, Any]) -> bytes:
    """The exact bytes written to ``build-provenance.json`` — canonical JSON + a trailing newline,
    identical across the API and worker builds."""
    return (canonical_json(document) + "\n").encode()


def document_sha256(document: dict[str, Any]) -> str:
    return hashlib.sha256(render_document(document)).hexdigest()
