"""provider activation onboarding matrix columns

Revision ID: 43b334ddd564
Revises: 8cda46a52c82
Create Date: 2026-07-23 21:41:46.167253

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43b334ddd564'
down_revision: str | None = '8cda46a52c82'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_activation', sa.Column('intended_role', sa.Text(), nullable=True))
    op.add_column('provider_activation', sa.Column('catalog_scope', sa.Text(), nullable=True))
    op.add_column('provider_activation', sa.Column('activation_state', sa.Text(), server_default='disabled', nullable=False))
    op.add_column('provider_activation', sa.Column('expected_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_activation', 'expected_capabilities')
    op.drop_column('provider_activation', 'activation_state')
    op.drop_column('provider_activation', 'catalog_scope')
    op.drop_column('provider_activation', 'intended_role')
    # ### end Alembic commands ###
