"""mapping enrichment fields

Revision ID: cae826099316
Revises: d1e2f3a4b5c6
Create Date: 2026-07-24 10:18:15.172262

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae826099316'
down_revision: str | None = 'd1e2f3a4b5c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_ingredient_mapping', sa.Column('enrichment_status', sa.Text(), server_default='not_requested', nullable=False))
    op.add_column('provider_ingredient_mapping', sa.Column('enrichment_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('provider_ingredient_mapping', sa.Column('enrichment_requested_by', sa.BigInteger(), nullable=True))
    op.add_column('provider_ingredient_mapping', sa.Column('enrichment_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('provider_ingredient_mapping', sa.Column('provider_endpoint', sa.Text(), nullable=True))
    op.add_column('provider_ingredient_mapping', sa.Column('enrichment_error_category', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'provider_ingredient_mapping', 'user', ['enrichment_requested_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider_ingredient_mapping', type_='foreignkey')
    op.drop_column('provider_ingredient_mapping', 'enrichment_error_category')
    op.drop_column('provider_ingredient_mapping', 'provider_endpoint')
    op.drop_column('provider_ingredient_mapping', 'enrichment_completed_at')
    op.drop_column('provider_ingredient_mapping', 'enrichment_requested_by')
    op.drop_column('provider_ingredient_mapping', 'enrichment_requested_at')
    op.drop_column('provider_ingredient_mapping', 'enrichment_status')
    # ### end Alembic commands ###
