"""authorization identity and expected backup on remediation run

Revision ID: 35d510ebc887
Revises: 360a55cb6abb
Create Date: 2026-07-27 13:12:44.622514

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d510ebc887'
down_revision: str | None = '360a55cb6abb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_remediation_run', sa.Column('authorization_id', sa.Text(), nullable=True))
    op.add_column('history_remediation_run', sa.Column('authorization_package_hash', sa.Text(), nullable=True))
    op.add_column('history_remediation_run', sa.Column('authorization_key_fingerprint', sa.Text(), nullable=True))
    op.add_column('history_remediation_run', sa.Column('authorization_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('history_remediation_run', sa.Column('authorization_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('history_remediation_run', sa.Column('expected_backup_sha256', sa.Text(), nullable=True))
    op.add_column('history_remediation_run', sa.Column('expected_backup_storage_reference_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_remediation_run', 'expected_backup_storage_reference_hash')
    op.drop_column('history_remediation_run', 'expected_backup_sha256')
    op.drop_column('history_remediation_run', 'authorization_expires_at')
    op.drop_column('history_remediation_run', 'authorization_generated_at')
    op.drop_column('history_remediation_run', 'authorization_key_fingerprint')
    op.drop_column('history_remediation_run', 'authorization_package_hash')
    op.drop_column('history_remediation_run', 'authorization_id')
    # ### end Alembic commands ###
