"""fase5 usage ledger metering

Revision ID: 405e472c04b3
Revises: ed4978952157
Create Date: 2026-07-22 13:11:23.842694

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '405e472c04b3'
down_revision: str | None = 'ed4978952157'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_ledger',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('household_id', sa.BigInteger(), nullable=True),
    sa.Column('optimization_run_id', sa.BigInteger(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('currency', sa.Text(), server_default='EUR', nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_run.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_household_created', 'usage_ledger', ['household_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_ledger_public_id'), 'usage_ledger', ['public_id'], unique=True)
    op.create_index('ix_usage_user_created', 'usage_ledger', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_user_created', table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_public_id'), table_name='usage_ledger')
    op.drop_index('ix_usage_household_created', table_name='usage_ledger')
    op.drop_table('usage_ledger')
    # ### end Alembic commands ###
