"""shadow comparison status + activation gates + provider ingredient mapping

Revision ID: 65ed47ab8bdd
Revises: 85e2efb9b772
Create Date: 2026-07-24 08:58:03.919378

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65ed47ab8bdd'
down_revision: str | None = '85e2efb9b772'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_ingredient_mapping',
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_ingredient_key', sa.Text(), nullable=False),
    sa.Column('provider_code', sa.Text(), nullable=False),
    sa.Column('retailer_slug', sa.Text(), nullable=False),
    sa.Column('external_product_id', sa.Text(), nullable=False),
    sa.Column('normalized_product_id', sa.BigInteger(), nullable=True),
    sa.Column('mapping_status', sa.Text(), server_default='candidate', nullable=False),
    sa.Column('mapping_method', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('semantic_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('lexical_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('category_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('unit_compatibility', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('preparation_compatibility', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('dietary_compatibility', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('allergen_compatibility', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('required_review', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['normalized_product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_ing_map_status', 'provider_ingredient_mapping', ['provider_code', 'mapping_status'], unique=False)
    op.create_index(op.f('ix_provider_ingredient_mapping_public_id'), 'provider_ingredient_mapping', ['public_id'], unique=True)
    op.create_index('ux_provider_ing_map', 'provider_ingredient_mapping', ['provider_code', 'ingredient_id', 'external_product_id'], unique=True)
    op.add_column('provider_activation', sa.Column('transport_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('provider_activation', sa.Column('capture_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('provider_activation', sa.Column('normalization_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('provider_activation', sa.Column('staging_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('provider_activation', sa.Column('shadow_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('provider_activation', sa.Column('production_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('provider_activation', sa.Column('production_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('shadow_evaluation_run', sa.Column('comparison_status', sa.Text(), server_default='failed', nullable=False))
    op.add_column('shadow_evaluation_run', sa.Column('comparison_blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('shadow_evaluation_run', sa.Column('known_cost_ingredient_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('shadow_evaluation_run', sa.Column('unknown_cost_ingredient_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('shadow_evaluation_run', sa.Column('known_cost_ratio', sa.Numeric(precision=5, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shadow_evaluation_run', 'known_cost_ratio')
    op.drop_column('shadow_evaluation_run', 'unknown_cost_ingredient_count')
    op.drop_column('shadow_evaluation_run', 'known_cost_ingredient_count')
    op.drop_column('shadow_evaluation_run', 'comparison_blockers')
    op.drop_column('shadow_evaluation_run', 'comparison_status')
    op.drop_column('provider_activation', 'production_approved')
    op.drop_column('provider_activation', 'production_enabled')
    op.drop_column('provider_activation', 'shadow_enabled')
    op.drop_column('provider_activation', 'staging_enabled')
    op.drop_column('provider_activation', 'normalization_enabled')
    op.drop_column('provider_activation', 'capture_enabled')
    op.drop_column('provider_activation', 'transport_enabled')
    op.drop_index('ux_provider_ing_map', table_name='provider_ingredient_mapping')
    op.drop_index(op.f('ix_provider_ingredient_mapping_public_id'), table_name='provider_ingredient_mapping')
    op.drop_index('ix_provider_ing_map_status', table_name='provider_ingredient_mapping')
    op.drop_table('provider_ingredient_mapping')
    # ### end Alembic commands ###
