"""fase_a_ingestion_foundation

Revision ID: 1f9cf8405c1b
Revises: 8b383e438078
Create Date: 2026-07-22 20:40:43.105412

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f9cf8405c1b'
down_revision: str | None = '8b383e438078'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_state',
    sa.Column('retailer_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('connector_version', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'degraded', 'disabled', 'unsupported', 'permission_required', 'temporarily_blocked', 'parser_broken', 'source_unavailable', 'partial_only', name='connector_state_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('circuit_open_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_state_public_id'), 'connector_state', ['public_id'], unique=True)
    op.create_index('ux_connector_state_scope', 'connector_state', ['retailer_id', 'store_id', 'connector_version'], unique=True)
    op.create_table('coverage_snapshot',
    sa.Column('retailer_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_products', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('discovered_products', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('priced_products', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fresh_prices', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stale_prices', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('estimated_prices', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unavailable_products', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('coverage_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('weighted_coverage_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.Enum('complete', 'high', 'partial', 'insufficient', 'stale', 'none', name='coverage_snapshot_status', native_enum=False), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_snapshot_public_id'), 'coverage_snapshot', ['public_id'], unique=True)
    op.create_index('ix_coverage_snapshot_retailer_observed', 'coverage_snapshot', ['retailer_id', 'observed_at'], unique=False)
    op.create_table('crawl_run',
    sa.Column('retailer_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('run_type', sa.Enum('discovery', 'catalog', 'prices', 'offers', 'health', name='crawl_run_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', name='crawl_run_status', native_enum=False), server_default='queued', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fetched_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('parsed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('accepted_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rejected_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('quarantined_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('coverage_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('connector_version', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_run_public_id'), 'crawl_run', ['public_id'], unique=True)
    op.create_index('ix_crawl_run_retailer_status', 'crawl_run', ['retailer_id', 'status'], unique=False)
    op.create_index('ix_crawl_run_scheduled', 'crawl_run', ['scheduled_at'], unique=False)
    op.create_table('external_product',
    sa.Column('retailer_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('canonical_product_id', sa.BigInteger(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_product_public_id'), 'external_product', ['public_id'], unique=True)
    op.create_index('ux_external_product_retailer_external', 'external_product', ['retailer_id', 'external_id'], unique=True)
    op.create_table('store_resolution',
    sa.Column('requested_postal_code', sa.Text(), nullable=True),
    sa.Column('requested_store_id', sa.BigInteger(), nullable=True),
    sa.Column('resolved_retailer_id', sa.BigInteger(), nullable=False),
    sa.Column('resolved_store_id', sa.BigInteger(), nullable=True),
    sa.Column('external_store_id', sa.Text(), nullable=True),
    sa.Column('delivery_zone_id', sa.BigInteger(), nullable=True),
    sa.Column('scope', sa.Enum('exact_store', 'delivery_zone', 'postal_code', 'municipality', 'province', 'region', 'national', 'unknown', name='store_resolution_scope', native_enum=False), nullable=False),
    sa.Column('resolution_method', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_retailer_id'], ['retailer.id'], ),
    sa.ForeignKeyConstraint(['resolved_store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_store_resolution_postal', 'store_resolution', ['requested_postal_code'], unique=False)
    op.create_index(op.f('ix_store_resolution_public_id'), 'store_resolution', ['public_id'], unique=True)
    op.create_index('ix_store_resolution_resolved_store', 'store_resolution', ['resolved_store_id'], unique=False)
    op.create_table('crawl_job',
    sa.Column('crawl_run_id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('queued', 'locked', 'completed', 'failed', 'dead_letter', 'cancelled', name='crawl_job_status', native_enum=False), server_default='queued', nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_job_public_id'), 'crawl_job', ['public_id'], unique=True)
    op.create_index('ix_crawl_job_queue', 'crawl_job', ['status', 'available_at', 'priority'], unique=False)
    op.create_index('ix_crawl_job_run', 'crawl_job', ['crawl_run_id'], unique=False)
    op.create_table('product_variant',
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('retailer_id', sa.BigInteger(), nullable=False),
    sa.Column('external_product_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('package_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('package_unit', sa.Text(), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('sell_unit', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['external_product_id'], ['external_product.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_variant_external_product', 'product_variant', ['external_product_id'], unique=False)
    op.create_index(op.f('ix_product_variant_public_id'), 'product_variant', ['public_id'], unique=True)
    op.create_index('ix_product_variant_retailer', 'product_variant', ['retailer_id'], unique=False)
    op.create_table('raw_capture',
    sa.Column('crawl_run_id', sa.BigInteger(), nullable=True),
    sa.Column('retailer_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('request_method', sa.Text(), server_default='GET', nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('content_encoding', sa.Text(), nullable=True),
    sa.Column('body_hash', sa.Text(), nullable=False),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body_data', sa.LargeBinary(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_block_page', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('retention_policy', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_run.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_capture_body_hash', 'raw_capture', ['body_hash'], unique=False)
    op.create_index(op.f('ix_raw_capture_public_id'), 'raw_capture', ['public_id'], unique=True)
    op.create_index('ix_raw_capture_retailer_captured', 'raw_capture', ['retailer_id', 'captured_at'], unique=False)
    op.create_table('price_observation',
    sa.Column('retailer_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_zone_id', sa.BigInteger(), nullable=True),
    sa.Column('product_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('price_scope', sa.Enum('exact_store', 'delivery_zone', 'postal_code', 'municipality', 'province', 'region', 'national', 'unknown', name='price_observation_scope', native_enum=False), nullable=False),
    sa.Column('price_type', sa.Enum('regular', 'promotional', 'loyalty', 'manual', 'receipt', 'estimated', 'unknown', name='price_observation_type', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('unit_code', sa.Text(), nullable=True),
    sa.Column('promotion_text', sa.Text(), nullable=True),
    sa.Column('requires_loyalty', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('promotion_valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promotion_valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('raw_capture_id', sa.BigInteger(), nullable=True),
    sa.Column('crawl_run_id', sa.BigInteger(), nullable=True),
    sa.Column('connector_version', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'machine_verified', 'human_verified', 'disputed', name='price_observation_verification_status', native_enum=False), server_default='unverified', nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_run.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['raw_capture_id'], ['raw_capture.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_obs_retailer_store_observed', 'price_observation', ['retailer_id', 'store_id', 'observed_at'], unique=False)
    op.create_index('ix_price_obs_variant_valid_from', 'price_observation', ['product_variant_id', 'valid_from'], unique=False)
    op.create_index(op.f('ix_price_observation_public_id'), 'price_observation', ['public_id'], unique=True)
    op.create_table('price_anomaly',
    sa.Column('price_observation_id', sa.BigInteger(), nullable=True),
    sa.Column('crawl_run_id', sa.BigInteger(), nullable=True),
    sa.Column('anomaly_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='price_anomaly_severity', native_enum=False), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('open', 'quarantined', 'approved', 'rejected', name='price_anomaly_status', native_enum=False), server_default='open', nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_run.id'], ),
    sa.ForeignKeyConstraint(['price_observation_id'], ['price_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_anomaly_observation', 'price_anomaly', ['price_observation_id'], unique=False)
    op.create_index(op.f('ix_price_anomaly_public_id'), 'price_anomaly', ['public_id'], unique=True)
    op.create_index('ix_price_anomaly_status', 'price_anomaly', ['status'], unique=False)
    op.create_table('promotion_rule',
    sa.Column('price_observation_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('percentage', 'fixed', 'nxm', 'second_unit', 'min_quantity', 'pack', name='promotion_rule_type', native_enum=False), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=True),
    sa.Column('charged_quantity', sa.Integer(), nullable=True),
    sa.Column('percentage_discount', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('fixed_discount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('loyalty_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['price_observation_id'], ['price_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_promotion_rule_observation', 'promotion_rule', ['price_observation_id'], unique=False)
    op.create_index(op.f('ix_promotion_rule_public_id'), 'promotion_rule', ['public_id'], unique=True)
    op.add_column('data_source', sa.Column('legal_status', sa.Enum('unknown', 'public', 'authorized', 'permission_required', 'prohibited', name='data_source_legal_status', native_enum=False), server_default='unknown', nullable=False))
    op.add_column('data_source', sa.Column('terms_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('data_source', sa.Column('robots_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('data_source', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source', 'notes')
    op.drop_column('data_source', 'robots_reviewed_at')
    op.drop_column('data_source', 'terms_reviewed_at')
    op.drop_column('data_source', 'legal_status')
    op.drop_index(op.f('ix_promotion_rule_public_id'), table_name='promotion_rule')
    op.drop_index('ix_promotion_rule_observation', table_name='promotion_rule')
    op.drop_table('promotion_rule')
    op.drop_index('ix_price_anomaly_status', table_name='price_anomaly')
    op.drop_index(op.f('ix_price_anomaly_public_id'), table_name='price_anomaly')
    op.drop_index('ix_price_anomaly_observation', table_name='price_anomaly')
    op.drop_table('price_anomaly')
    op.drop_index(op.f('ix_price_observation_public_id'), table_name='price_observation')
    op.drop_index('ix_price_obs_variant_valid_from', table_name='price_observation')
    op.drop_index('ix_price_obs_retailer_store_observed', table_name='price_observation')
    op.drop_table('price_observation')
    op.drop_index('ix_raw_capture_retailer_captured', table_name='raw_capture')
    op.drop_index(op.f('ix_raw_capture_public_id'), table_name='raw_capture')
    op.drop_index('ix_raw_capture_body_hash', table_name='raw_capture')
    op.drop_table('raw_capture')
    op.drop_index('ix_product_variant_retailer', table_name='product_variant')
    op.drop_index(op.f('ix_product_variant_public_id'), table_name='product_variant')
    op.drop_index('ix_product_variant_external_product', table_name='product_variant')
    op.drop_table('product_variant')
    op.drop_index('ix_crawl_job_run', table_name='crawl_job')
    op.drop_index('ix_crawl_job_queue', table_name='crawl_job')
    op.drop_index(op.f('ix_crawl_job_public_id'), table_name='crawl_job')
    op.drop_table('crawl_job')
    op.drop_index('ix_store_resolution_resolved_store', table_name='store_resolution')
    op.drop_index(op.f('ix_store_resolution_public_id'), table_name='store_resolution')
    op.drop_index('ix_store_resolution_postal', table_name='store_resolution')
    op.drop_table('store_resolution')
    op.drop_index('ux_external_product_retailer_external', table_name='external_product')
    op.drop_index(op.f('ix_external_product_public_id'), table_name='external_product')
    op.drop_table('external_product')
    op.drop_index('ix_crawl_run_scheduled', table_name='crawl_run')
    op.drop_index('ix_crawl_run_retailer_status', table_name='crawl_run')
    op.drop_index(op.f('ix_crawl_run_public_id'), table_name='crawl_run')
    op.drop_table('crawl_run')
    op.drop_index('ix_coverage_snapshot_retailer_observed', table_name='coverage_snapshot')
    op.drop_index(op.f('ix_coverage_snapshot_public_id'), table_name='coverage_snapshot')
    op.drop_table('coverage_snapshot')
    op.drop_index('ux_connector_state_scope', table_name='connector_state')
    op.drop_index(op.f('ix_connector_state_public_id'), table_name='connector_state')
    op.drop_table('connector_state')
    # ### end Alembic commands ###
