"""household invitations

Revision ID: 8b383e438078
Revises: b1c2d3e4f5a6
Create Date: 2026-07-22 18:44:12.933336

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b383e438078'
down_revision: str | None = 'b1c2d3e4f5a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_invitation',
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('editor', 'viewer', name='invitation_role', native_enum=False), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'revoked', 'expired', name='invitation_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('invited_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_invitation_public_id'), 'household_invitation', ['public_id'], unique=True)
    op.create_index('ix_invitation_household', 'household_invitation', ['household_id'], unique=False)
    op.create_index('ux_invitation_pending', 'household_invitation', ['household_id', 'email'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ux_invitation_token_hash', 'household_invitation', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_invitation_token_hash', table_name='household_invitation')
    op.drop_index('ux_invitation_pending', table_name='household_invitation', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_invitation_household', table_name='household_invitation')
    op.drop_index(op.f('ix_household_invitation_public_id'), table_name='household_invitation')
    op.drop_table('household_invitation')
    # ### end Alembic commands ###
