"""provider usage accounting table

Revision ID: 7c1479d7c41d
Revises: f549b465d14b
Create Date: 2026-07-23 14:56:15.613454

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1479d7c41d'
down_revision: str | None = 'f549b465d14b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_usage',
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('request_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('product_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawl_run_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_usage_provider_started', 'provider_usage', ['provider', 'started_at'], unique=False)
    op.create_index(op.f('ix_provider_usage_public_id'), 'provider_usage', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_usage_public_id'), table_name='provider_usage')
    op.drop_index('ix_provider_usage_provider_started', table_name='provider_usage')
    op.drop_table('provider_usage')
    # ### end Alembic commands ###
