"""mapping version + supersede + review reason

Revision ID: 8026415c5fd5
Revises: 65ed47ab8bdd
Create Date: 2026-07-24 09:30:18.601563

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8026415c5fd5'
down_revision: str | None = '65ed47ab8bdd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_ingredient_mapping', sa.Column('review_reason', sa.Text(), nullable=True))
    op.add_column('provider_ingredient_mapping', sa.Column('mapping_version', sa.Text(), server_default='1.0.0', nullable=False))
    op.add_column('provider_ingredient_mapping', sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('provider_ingredient_mapping', sa.Column('superseded_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_ingredient_mapping', 'superseded_reason')
    op.drop_column('provider_ingredient_mapping', 'superseded_at')
    op.drop_column('provider_ingredient_mapping', 'mapping_version')
    op.drop_column('provider_ingredient_mapping', 'review_reason')
    # ### end Alembic commands ###
