"""slice: relative_serving + favorites/feedback

Revision ID: 9a988070cece
Revises: 8f156e742146
Create Date: 2026-07-22 00:08:02.053906

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a988070cece'
down_revision: str | None = '8f156e742146'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_recipe',
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_favorite_household', 'favorite_recipe', ['household_id'], unique=False)
    op.create_index(op.f('ix_favorite_recipe_public_id'), 'favorite_recipe', ['public_id'], unique=True)
    op.create_index('ux_favorite_household_recipe_user', 'favorite_recipe', ['household_id', 'recipe_id', 'user_id'], unique=True)
    op.create_table('recipe_feedback',
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('sentiment', sa.Enum('like', 'reject', 'no_show', name='recipe_feedback_sentiment', native_enum=False), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_household', 'recipe_feedback', ['household_id'], unique=False)
    op.create_index(op.f('ix_recipe_feedback_public_id'), 'recipe_feedback', ['public_id'], unique=True)
    op.create_index('ux_feedback_household_recipe_user', 'recipe_feedback', ['household_id', 'recipe_id', 'user_id'], unique=True)
    op.add_column('household_member', sa.Column('relative_serving', sa.Numeric(precision=5, scale=2), server_default=sa.text('1.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('household_member', 'relative_serving')
    op.drop_index('ux_feedback_household_recipe_user', table_name='recipe_feedback')
    op.drop_index(op.f('ix_recipe_feedback_public_id'), table_name='recipe_feedback')
    op.drop_index('ix_feedback_household', table_name='recipe_feedback')
    op.drop_table('recipe_feedback')
    op.drop_index('ux_favorite_household_recipe_user', table_name='favorite_recipe')
    op.drop_index(op.f('ix_favorite_recipe_public_id'), table_name='favorite_recipe')
    op.drop_index('ix_favorite_household', table_name='favorite_recipe')
    op.drop_table('favorite_recipe')
    # ### end Alembic commands ###
