"""initial vertical-slice schema

Revision ID: 8f156e742146
Revises: 
Create Date: 2026-07-21 23:39:05.125911

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f156e742146'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('official', 'authorized_partner', 'community_connector', 'open_dataset', 'admin_import', 'manual_entry', 'user_receipt', 'estimated', 'demo', name='data_source_source_type', native_enum=False), nullable=False),
    sa.Column('adapter_key', sa.Text(), nullable=True),
    sa.Column('license_code', sa.Text(), nullable=True),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_public_id'), 'data_source', ['public_id'], unique=True)
    op.create_index('ux_data_source_slug', 'data_source', ['slug'], unique=True)
    op.create_table('ingredient',
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('category_code', sa.Text(), nullable=True),
    sa.Column('default_unit', sa.Text(), nullable=True),
    sa.Column('density_g_per_ml', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('allergen_codes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_public_id'), 'ingredient', ['public_id'], unique=True)
    op.create_index('ux_ingredient_canonical', 'ingredient', ['canonical_name'], unique=True)
    op.create_table('retailer',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('adapter_key', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), server_default='ES', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_public_id'), 'retailer', ['public_id'], unique=True)
    op.create_index('ux_retailer_slug', 'retailer', ['slug'], unique=True)
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), server_default='es-ES', nullable=False),
    sa.Column('ai_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'anonymized', name='user_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_public_id'), 'user', ['public_id'], unique=True)
    op.create_index('ux_user_email', 'user', ['email'], unique=True)
    op.create_table('product',
    sa.Column('retailer_id', sa.BigInteger(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('package_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('package_unit', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_public_id'), 'product', ['public_id'], unique=True)
    op.create_index('ux_product_retailer_external', 'product', ['retailer_id', 'external_id'], unique=True, postgresql_where=sa.text('retailer_id IS NOT NULL AND external_id IS NOT NULL'))
    op.create_table('store',
    sa.Column('retailer_id', sa.BigInteger(), nullable=False),
    sa.Column('external_code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('catalog_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_coverage_hint', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_public_id'), 'store', ['public_id'], unique=True)
    op.create_index('ix_store_retailer_postal', 'store', ['retailer_id', 'postal_code'], unique=False)
    op.create_index('ux_store_retailer_external', 'store', ['retailer_id', 'external_code'], unique=True, postgresql_where=sa.text('external_code IS NOT NULL'))
    op.create_table('user_session',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.LargeBinary(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_user_active', 'user_session', ['user_id', 'expires_at'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index(op.f('ix_user_session_public_id'), 'user_session', ['public_id'], unique=True)
    op.create_index('ux_session_token_hash', 'user_session', ['token_hash'], unique=True)
    op.create_table('household',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('default_retailer_id', sa.BigInteger(), nullable=True),
    sa.Column('default_store_id', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.Text(), server_default='EUR', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_retailer_id'], ['retailer.id'], ),
    sa.ForeignKeyConstraint(['default_store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_public_id'), 'household', ['public_id'], unique=True)
    op.create_table('ingredient_product_mapping',
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('retailer_id', sa.BigInteger(), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('preference_rank', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ing_map_ingredient_rank', 'ingredient_product_mapping', ['ingredient_id', 'preference_rank'], unique=False)
    op.create_index(op.f('ix_ingredient_product_mapping_public_id'), 'ingredient_product_mapping', ['public_id'], unique=True)
    op.create_index('ux_ing_product', 'ingredient_product_mapping', ['ingredient_id', 'product_id'], unique=True)
    op.create_table('product_nutrition',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('basis_quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('basis_unit', sa.Text(), nullable=False),
    sa.Column('energy_kcal', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('carbohydrate_g', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('sugars_g', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('saturated_fat_g', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('salt_g', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('allergens', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('traces', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ingredients_text', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('official', 'authorized_partner', 'community_connector', 'open_dataset', 'admin_import', 'manual_entry', 'user_receipt', 'estimated', 'demo', name='nutrition_source_type', native_enum=False), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_nutrition_public_id'), 'product_nutrition', ['public_id'], unique=True)
    op.create_index('ux_nutrition_product', 'product_nutrition', ['product_id'], unique=True)
    op.create_table('product_price',
    sa.Column('retailer_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('package_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('package_unit', sa.Text(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('promotion', sa.Text(), nullable=True),
    sa.Column('availability', sa.Enum('in_stock', 'out_of_stock', 'unknown', name='price_availability', native_enum=False), nullable=True),
    sa.Column('source_type', sa.Enum('official', 'authorized_partner', 'community_connector', 'open_dataset', 'admin_import', 'manual_entry', 'user_receipt', 'estimated', 'demo', name='source_type', native_enum=False), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('import_id', sa.BigInteger(), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'machine_verified', 'human_verified', 'disputed', name='verification_status', native_enum=False), server_default='unverified', nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_expiry', 'product_price', ['expires_at'], unique=False, postgresql_where=sa.text('expires_at IS NOT NULL'))
    op.create_index('ix_price_import', 'product_price', ['import_id'], unique=False)
    op.create_index('ix_price_lookup', 'product_price', ['store_id', 'product_id', 'observed_at'], unique=False)
    op.create_index('ix_price_product_observed', 'product_price', ['product_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_product_price_public_id'), 'product_price', ['public_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('household_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_public_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_hash', sa.LargeBinary(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_time', 'audit_log', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_public_id'], unique=False)
    op.create_index(op.f('ix_audit_log_public_id'), 'audit_log', ['public_id'], unique=True)
    op.create_table('equipment',
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('equipment_code', sa.Text(), nullable=False),
    sa.Column('available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_public_id'), 'equipment', ['public_id'], unique=True)
    op.create_table('household_member',
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='member_role', native_enum=False), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_eater', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_member_public_id'), 'household_member', ['public_id'], unique=True)
    op.create_index('ix_member_user', 'household_member', ['user_id'], unique=False)
    op.create_index('ux_member_household_user', 'household_member', ['household_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('meal_plan',
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('retailer_id', sa.BigInteger(), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('currency', sa.Text(), server_default='EUR', nullable=False),
    sa.Column('status', sa.Enum('draft', 'generating', 'ready', 'failed', 'archived', name='meal_plan_status', native_enum=False), server_default='draft', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_public_id'), 'meal_plan', ['public_id'], unique=True)
    op.create_index('ix_plan_household_status', 'meal_plan', ['household_id', 'status'], unique=False)
    op.create_table('pantry_item',
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pantry_household_ingredient', 'pantry_item', ['household_id', 'ingredient_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_pantry_item_public_id'), 'pantry_item', ['public_id'], unique=True)
    op.create_table('recipe',
    sa.Column('household_id', sa.BigInteger(), nullable=True),
    sa.Column('origin', sa.Enum('seed', 'ai_generated', 'user', 'imported', name='recipe_origin', native_enum=False), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('meal_types', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('cuisine', sa.Text(), nullable=True),
    sa.Column('preference_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('preparation_minutes', sa.Integer(), nullable=True),
    sa.Column('cooking_minutes', sa.Integer(), nullable=True),
    sa.Column('required_equipment', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('leftover_reuse', sa.Text(), nullable=True),
    sa.Column('storage_instructions', sa.Text(), nullable=True),
    sa.Column('reheating_instructions', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_public_id'), 'recipe', ['public_id'], unique=True)
    op.create_table('dietary_profile',
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('household_member_id', sa.BigInteger(), nullable=True),
    sa.Column('diet_type', sa.Text(), nullable=True),
    sa.Column('energy_target_kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_target_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('carb_target_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fat_target_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_member_id'], ['household_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dietary_profile_public_id'), 'dietary_profile', ['public_id'], unique=True)
    op.create_index('ix_profile_household', 'dietary_profile', ['household_id'], unique=False)
    op.create_table('grocery_list',
    sa.Column('meal_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.Text(), server_default='EUR', nullable=False),
    sa.Column('known_cost_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('estimated_cost_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_coverage', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('weighted_price_coverage', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('coverage_status', sa.Enum('complete', 'high', 'partial', 'insufficient', 'stale', 'none', name='coverage_status', native_enum=False), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_list_public_id'), 'grocery_list', ['public_id'], unique=True)
    op.create_index('ux_grocery_list_plan', 'grocery_list', ['meal_plan_id'], unique=True)
    op.create_table('meal_requirement',
    sa.Column('meal_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'snack', 'dinner', name='requirement_meal_type', native_enum=False), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('default_servings', sa.Integer(), nullable=False),
    sa.Column('selected_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_distribute', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('preferred_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('maximum_preparation_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_tupper', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reheating_available', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_requirement_public_id'), 'meal_requirement', ['public_id'], unique=True)
    op.create_table('optimization_run',
    sa.Column('meal_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'collecting_data', 'generating_candidates', 'validating', 'optimizing', 'completed', 'failed', 'cancelled', name='optimization_run_status', native_enum=False), server_default='queued', nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('scoring_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('infeasibility_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_run_public_id'), 'optimization_run', ['public_id'], unique=True)
    op.create_table('recipe_ingredient',
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('optional', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('substitution_group', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipe_ing_recipe', 'recipe_ingredient', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredient_public_id'), 'recipe_ingredient', ['public_id'], unique=True)
    op.create_table('recipe_step',
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_step_public_id'), 'recipe_step', ['public_id'], unique=True)
    op.create_index('ux_recipe_step', 'recipe_step', ['recipe_id', 'step_number'], unique=True)
    op.create_table('allergy',
    sa.Column('dietary_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('allergen_code', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('intolerance', 'allergy', 'anaphylaxis', name='allergy_severity', native_enum=False), nullable=False),
    sa.Column('avoid_traces', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dietary_profile_id'], ['dietary_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_allergy_profile', 'allergy', ['dietary_profile_id'], unique=False)
    op.create_index(op.f('ix_allergy_public_id'), 'allergy', ['public_id'], unique=True)
    op.create_table('food_preference',
    sa.Column('dietary_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_type', sa.Enum('ingredient', 'cuisine', 'tag', name='preference_subject_type', native_enum=False), nullable=False),
    sa.Column('subject_ref', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.Enum('like', 'dislike', 'avoid', name='preference_sentiment', native_enum=False), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dietary_profile_id'], ['dietary_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_preference_public_id'), 'food_preference', ['public_id'], unique=True)
    op.create_table('generation_job',
    sa.Column('optimization_run_id', sa.BigInteger(), nullable=True),
    sa.Column('meal_plan_id', sa.BigInteger(), nullable=True),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'collecting_data', 'generating_candidates', 'validating', 'optimizing', 'completed', 'failed', 'cancelled', name='generation_job_status', native_enum=False), server_default='queued', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_job_public_id'), 'generation_job', ['public_id'], unique=True)
    op.create_index('ix_job_locked', 'generation_job', ['status', 'locked_at'], unique=False, postgresql_where=sa.text('locked_at IS NOT NULL'))
    op.create_index('ix_job_queue', 'generation_job', ['status', 'run_after'], unique=False)
    op.create_table('grocery_list_item',
    sa.Column('grocery_list_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=True),
    sa.Column('needed_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('pantry_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('pending_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('package_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('package_unit', sa.Text(), nullable=True),
    sa.Column('packages_selected', sa.Integer(), nullable=True),
    sa.Column('purchased_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('used_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('leftover_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('price_product_price_id', sa.BigInteger(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('recipe_attributable_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('marginal_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_status', sa.Enum('known', 'estimated', 'missing', 'stale', name='grocery_price_status', native_enum=False), nullable=False),
    sa.Column('is_checked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_list.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['price_product_price_id'], ['product_price.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gli_list', 'grocery_list_item', ['grocery_list_id'], unique=False)
    op.create_index(op.f('ix_grocery_list_item_public_id'), 'grocery_list_item', ['public_id'], unique=True)
    op.create_table('planned_meal',
    sa.Column('meal_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('meal_requirement_id', sa.BigInteger(), nullable=True),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'snack', 'dinner', name='planned_meal_type', native_enum=False), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'accepted', 'rejected', 'cooked', 'regenerating', name='planned_meal_status', native_enum=False), server_default='planned', nullable=False),
    sa.Column('is_batch_cook', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_requirement_id'], ['meal_requirement.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_meal_public_id'), 'planned_meal', ['public_id'], unique=True)
    op.create_index('ix_planned_plan_date', 'planned_meal', ['meal_plan_id', 'scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_planned_plan_date', table_name='planned_meal')
    op.drop_index(op.f('ix_planned_meal_public_id'), table_name='planned_meal')
    op.drop_table('planned_meal')
    op.drop_index(op.f('ix_grocery_list_item_public_id'), table_name='grocery_list_item')
    op.drop_index('ix_gli_list', table_name='grocery_list_item')
    op.drop_table('grocery_list_item')
    op.drop_index('ix_job_queue', table_name='generation_job')
    op.drop_index('ix_job_locked', table_name='generation_job', postgresql_where=sa.text('locked_at IS NOT NULL'))
    op.drop_index(op.f('ix_generation_job_public_id'), table_name='generation_job')
    op.drop_table('generation_job')
    op.drop_index(op.f('ix_food_preference_public_id'), table_name='food_preference')
    op.drop_table('food_preference')
    op.drop_index(op.f('ix_allergy_public_id'), table_name='allergy')
    op.drop_index('ix_allergy_profile', table_name='allergy')
    op.drop_table('allergy')
    op.drop_index('ux_recipe_step', table_name='recipe_step')
    op.drop_index(op.f('ix_recipe_step_public_id'), table_name='recipe_step')
    op.drop_table('recipe_step')
    op.drop_index(op.f('ix_recipe_ingredient_public_id'), table_name='recipe_ingredient')
    op.drop_index('ix_recipe_ing_recipe', table_name='recipe_ingredient')
    op.drop_table('recipe_ingredient')
    op.drop_index(op.f('ix_optimization_run_public_id'), table_name='optimization_run')
    op.drop_table('optimization_run')
    op.drop_index(op.f('ix_meal_requirement_public_id'), table_name='meal_requirement')
    op.drop_table('meal_requirement')
    op.drop_index('ux_grocery_list_plan', table_name='grocery_list')
    op.drop_index(op.f('ix_grocery_list_public_id'), table_name='grocery_list')
    op.drop_table('grocery_list')
    op.drop_index('ix_profile_household', table_name='dietary_profile')
    op.drop_index(op.f('ix_dietary_profile_public_id'), table_name='dietary_profile')
    op.drop_table('dietary_profile')
    op.drop_index(op.f('ix_recipe_public_id'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_pantry_item_public_id'), table_name='pantry_item')
    op.drop_index('ix_pantry_household_ingredient', table_name='pantry_item', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('pantry_item')
    op.drop_index('ix_plan_household_status', table_name='meal_plan')
    op.drop_index(op.f('ix_meal_plan_public_id'), table_name='meal_plan')
    op.drop_table('meal_plan')
    op.drop_index('ux_member_household_user', table_name='household_member', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('ix_member_user', table_name='household_member')
    op.drop_index(op.f('ix_household_member_public_id'), table_name='household_member')
    op.drop_table('household_member')
    op.drop_index(op.f('ix_equipment_public_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_audit_log_public_id'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_actor_time', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_product_price_public_id'), table_name='product_price')
    op.drop_index('ix_price_product_observed', table_name='product_price')
    op.drop_index('ix_price_lookup', table_name='product_price')
    op.drop_index('ix_price_import', table_name='product_price')
    op.drop_index('ix_price_expiry', table_name='product_price', postgresql_where=sa.text('expires_at IS NOT NULL'))
    op.drop_table('product_price')
    op.drop_index('ux_nutrition_product', table_name='product_nutrition')
    op.drop_index(op.f('ix_product_nutrition_public_id'), table_name='product_nutrition')
    op.drop_table('product_nutrition')
    op.drop_index('ux_ing_product', table_name='ingredient_product_mapping')
    op.drop_index(op.f('ix_ingredient_product_mapping_public_id'), table_name='ingredient_product_mapping')
    op.drop_index('ix_ing_map_ingredient_rank', table_name='ingredient_product_mapping')
    op.drop_table('ingredient_product_mapping')
    op.drop_index(op.f('ix_household_public_id'), table_name='household')
    op.drop_table('household')
    op.drop_index('ux_session_token_hash', table_name='user_session')
    op.drop_index(op.f('ix_user_session_public_id'), table_name='user_session')
    op.drop_index('ix_session_user_active', table_name='user_session', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('user_session')
    op.drop_index('ux_store_retailer_external', table_name='store', postgresql_where=sa.text('external_code IS NOT NULL'))
    op.drop_index('ix_store_retailer_postal', table_name='store')
    op.drop_index(op.f('ix_store_public_id'), table_name='store')
    op.drop_table('store')
    op.drop_index('ux_product_retailer_external', table_name='product', postgresql_where=sa.text('retailer_id IS NOT NULL AND external_id IS NOT NULL'))
    op.drop_index(op.f('ix_product_public_id'), table_name='product')
    op.drop_table('product')
    op.drop_index('ux_user_email', table_name='user')
    op.drop_index(op.f('ix_user_public_id'), table_name='user')
    op.drop_table('user')
    op.drop_index('ux_retailer_slug', table_name='retailer')
    op.drop_index(op.f('ix_retailer_public_id'), table_name='retailer')
    op.drop_table('retailer')
    op.drop_index('ux_ingredient_canonical', table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_public_id'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index('ux_data_source_slug', table_name='data_source')
    op.drop_index(op.f('ix_data_source_public_id'), table_name='data_source')
    op.drop_table('data_source')
    # ### end Alembic commands ###
