"""history remediation audit tables

Revision ID: 360a55cb6abb
Revises: b3c4d5e6f7a8
Create Date: 2026-07-26 22:37:14.935396

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '360a55cb6abb'
down_revision: str | None = 'b3c4d5e6f7a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_remediation_run',
    sa.Column('plan_hash', sa.Text(), nullable=False),
    sa.Column('manifest_schema_version', sa.BigInteger(), nullable=False),
    sa.Column('planner_tool_version', sa.Text(), nullable=False),
    sa.Column('planner_source_hash', sa.Text(), nullable=False),
    sa.Column('writer_contract_version', sa.Text(), nullable=False),
    sa.Column('main_commit_sha', sa.Text(), nullable=False),
    sa.Column('alembic_revision', sa.Text(), nullable=False),
    sa.Column('execution_mode', sa.Enum('verify_only', 'simulate', 'apply', 'restore', name='history_remediation_mode', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'simulated', 'applied', 'failed', 'restored', 'rolled_back', name='history_remediation_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operator_reference', sa.Text(), nullable=True),
    sa.Column('expected_commit_sha', sa.Text(), nullable=True),
    sa.Column('observed_commit_sha', sa.Text(), nullable=True),
    sa.Column('expected_source_hash', sa.Text(), nullable=True),
    sa.Column('observed_source_hash', sa.Text(), nullable=True),
    sa.Column('expected_api_artifact_hash', sa.Text(), nullable=True),
    sa.Column('observed_api_artifact_hash', sa.Text(), nullable=True),
    sa.Column('expected_worker_artifact_hash', sa.Text(), nullable=True),
    sa.Column('observed_worker_artifact_hash', sa.Text(), nullable=True),
    sa.Column('provenance_document_hash', sa.Text(), nullable=True),
    sa.Column('backup_sha256', sa.Text(), nullable=True),
    sa.Column('backup_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('backup_postgres_version', sa.Text(), nullable=True),
    sa.Column('backup_pg_restore_version', sa.Text(), nullable=True),
    sa.Column('backup_database_version', sa.Text(), nullable=True),
    sa.Column('backup_dump_database_version', sa.Text(), nullable=True),
    sa.Column('backup_restore_list_verified', sa.Boolean(), nullable=True),
    sa.Column('backup_permissions_verified', sa.Boolean(), nullable=True),
    sa.Column('backup_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backup_storage_reference', sa.Text(), nullable=True),
    sa.Column('backup_evidence_hash', sa.Text(), nullable=True),
    sa.Column('post_apply_occurrence_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('post_apply_supported_fk_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discovered_fk_fingerprint', sa.Text(), nullable=True),
    sa.Column('expected_unknown_fk_count', sa.BigInteger(), nullable=True),
    sa.Column('before_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_hash', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('restore_status', sa.Enum('none', 'restored', 'restore_failed', 'manual_review_required', name='history_remediation_restore_status', native_enum=False), server_default='none', nullable=False),
    sa.Column('supersedes_run_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_run_id'], ['history_remediation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_history_remediation_run_plan_hash', 'history_remediation_run', ['plan_hash'], unique=False)
    op.create_index(op.f('ix_history_remediation_run_public_id'), 'history_remediation_run', ['public_id'], unique=True)
    op.create_index('ix_history_remediation_run_status', 'history_remediation_run', ['status'], unique=False)
    op.create_index('uq_history_remediation_run_applied_plan', 'history_remediation_run', ['plan_hash'], unique=True, postgresql_where=sa.text("status = 'applied'"))
    op.create_index('uq_history_remediation_run_supersedes', 'history_remediation_run', ['supersedes_run_id'], unique=True, postgresql_where=sa.text('supersedes_run_id IS NOT NULL'))
    op.create_table('history_remediation_plan_consumption',
    sa.Column('plan_hash', sa.Text(), nullable=False),
    sa.Column('first_run_id', sa.BigInteger(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_hash', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_run_id'], ['history_remediation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_remediation_plan_consumption_public_id'), 'history_remediation_plan_consumption', ['public_id'], unique=True)
    op.create_index('uq_history_remediation_plan_consumption', 'history_remediation_plan_consumption', ['plan_hash'], unique=True)
    op.create_table('history_remediation_change',
    sa.Column('remediation_run_id', sa.BigInteger(), nullable=False),
    sa.Column('deterministic_action_id', sa.Text(), nullable=False),
    sa.Column('lane_fingerprint', sa.Text(), nullable=False),
    sa.Column('price_observation_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('original_temporal_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_bound_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('original_hash', sa.Text(), nullable=False),
    sa.Column('expected_bound_hash', sa.Text(), nullable=False),
    sa.Column('actual_after_hash', sa.Text(), nullable=True),
    sa.Column('restore_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_anomaly_original_id', sa.BigInteger(), nullable=True),
    sa.Column('created_anomaly_hash', sa.Text(), nullable=True),
    sa.Column('created_anomaly_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_anomaly_live_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'applied', 'restored', 'failed', name='history_remediation_change_status', native_enum=False), server_default='planned', nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_anomaly_live_id'], ['price_anomaly.id'], ),
    sa.ForeignKeyConstraint(['remediation_run_id'], ['history_remediation_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remediation_run_id', 'deterministic_action_id', name='uq_history_remediation_change_action')
    )
    op.create_index('ix_history_remediation_change_observation', 'history_remediation_change', ['price_observation_id'], unique=False)
    op.create_index(op.f('ix_history_remediation_change_public_id'), 'history_remediation_change', ['public_id'], unique=True)
    op.create_index('ix_history_remediation_change_run', 'history_remediation_change', ['remediation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_history_remediation_change_run', table_name='history_remediation_change')
    op.drop_index(op.f('ix_history_remediation_change_public_id'), table_name='history_remediation_change')
    op.drop_index('ix_history_remediation_change_observation', table_name='history_remediation_change')
    op.drop_table('history_remediation_change')
    op.drop_index('uq_history_remediation_plan_consumption', table_name='history_remediation_plan_consumption')
    op.drop_index(op.f('ix_history_remediation_plan_consumption_public_id'), table_name='history_remediation_plan_consumption')
    op.drop_table('history_remediation_plan_consumption')
    op.drop_index('uq_history_remediation_run_supersedes', table_name='history_remediation_run', postgresql_where=sa.text('supersedes_run_id IS NOT NULL'))
    op.drop_index('uq_history_remediation_run_applied_plan', table_name='history_remediation_run', postgresql_where=sa.text("status = 'applied'"))
    op.drop_index('ix_history_remediation_run_status', table_name='history_remediation_run')
    op.drop_index(op.f('ix_history_remediation_run_public_id'), table_name='history_remediation_run')
    op.drop_index('ix_history_remediation_run_plan_hash', table_name='history_remediation_run')
    op.drop_table('history_remediation_run')
    # ### end Alembic commands ###
