"""provider activation gate table

Revision ID: b0ac30649f65
Revises: 7c1479d7c41d
Create Date: 2026-07-23 15:24:57.172542

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ac30649f65'
down_revision: str | None = '7c1479d7c41d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_activation',
    sa.Column('provider_code', sa.Text(), nullable=False),
    sa.Column('transport_status', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('mapper_status', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('data_quality_status', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('data_rights_status', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('development_only', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('production_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('production_approved_by', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_approved_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_activation_public_id'), 'provider_activation', ['public_id'], unique=True)
    op.create_index('ux_provider_activation_code', 'provider_activation', ['provider_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_provider_activation_code', table_name='provider_activation')
    op.drop_index(op.f('ix_provider_activation_public_id'), table_name='provider_activation')
    op.drop_table('provider_activation')
    # ### end Alembic commands ###
