"""licensed catalog: variant net content + mapping review + supplier field mapping

Revision ID: f549b465d14b
Revises: 1f9cf8405c1b
Create Date: 2026-07-23 12:46:11.578193

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f549b465d14b'
down_revision: str | None = '1f9cf8405c1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_field_mapping',
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('data_source_id', sa.BigInteger(), nullable=True),
    sa.Column('field_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit_aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_currency', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_field_mapping_public_id'), 'supplier_field_mapping', ['public_id'], unique=True)
    op.create_index('ux_supplier_field_mapping_source_name', 'supplier_field_mapping', ['source_name'], unique=True)
    op.add_column('ingredient_product_mapping', sa.Column('product_variant_id', sa.BigInteger(), nullable=True))
    op.add_column('ingredient_product_mapping', sa.Column('match_method', sa.Text(), nullable=True))
    op.add_column('ingredient_product_mapping', sa.Column('verification_status', sa.Enum('unverified', 'machine_verified', 'human_verified', 'disputed', name='ing_map_verification_status', native_enum=False), server_default='unverified', nullable=False))
    op.add_column('ingredient_product_mapping', sa.Column('verified_by', sa.BigInteger(), nullable=True))
    op.add_column('ingredient_product_mapping', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'ingredient_product_mapping', 'product_variant', ['product_variant_id'], ['id'])
    op.create_foreign_key(None, 'ingredient_product_mapping', 'user', ['verified_by'], ['id'])
    op.add_column('product_variant', sa.Column('net_content_quantity', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('product_variant', sa.Column('net_content_unit', sa.Text(), nullable=True))
    op.add_column('product_variant', sa.Column('variable_weight', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('product_variant', sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('product_variant', sa.Column('unit_price_unit', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variant', 'unit_price_unit')
    op.drop_column('product_variant', 'unit_price')
    op.drop_column('product_variant', 'variable_weight')
    op.drop_column('product_variant', 'net_content_unit')
    op.drop_column('product_variant', 'net_content_quantity')
    op.drop_constraint(None, 'ingredient_product_mapping', type_='foreignkey')
    op.drop_constraint(None, 'ingredient_product_mapping', type_='foreignkey')
    op.drop_column('ingredient_product_mapping', 'verified_at')
    op.drop_column('ingredient_product_mapping', 'verified_by')
    op.drop_column('ingredient_product_mapping', 'verification_status')
    op.drop_column('ingredient_product_mapping', 'match_method')
    op.drop_column('ingredient_product_mapping', 'product_variant_id')
    op.drop_index('ux_supplier_field_mapping_source_name', table_name='supplier_field_mapping')
    op.drop_index(op.f('ix_supplier_field_mapping_public_id'), table_name='supplier_field_mapping')
    op.drop_table('supplier_field_mapping')
    # ### end Alembic commands ###
