"""fase4: data imports, barcodes, admin

Revision ID: ed4978952157
Revises: 9a988070cece
Create Date: 2026-07-22 12:10:21.375200

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed4978952157'
down_revision: str | None = '9a988070cece'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_import',
    sa.Column('retailer_id', sa.BigInteger(), nullable=True),
    sa.Column('data_source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.Enum('official', 'authorized_partner', 'community_connector', 'open_dataset', 'admin_import', 'manual_entry', 'user_receipt', 'estimated', 'demo', name='data_import_source_type', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('pending', 'validating', 'dry_run', 'committed', 'rolled_back', 'failed', name='data_import_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('format', sa.Enum('csv', 'json', name='data_import_format', native_enum=False), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ok_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dry_run', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_import_created_by', 'data_import', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_data_import_public_id'), 'data_import', ['public_id'], unique=True)
    op.create_index('ix_data_import_status', 'data_import', ['status'], unique=False)
    op.create_table('product_barcode',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_barcode_code', 'product_barcode', ['barcode'], unique=False)
    op.create_index(op.f('ix_product_barcode_public_id'), 'product_barcode', ['public_id'], unique=True)
    op.create_index('ux_barcode_product', 'product_barcode', ['product_id', 'barcode'], unique=True)
    op.add_column('product', sa.Column('category_code', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_column('product', 'category_code')
    op.drop_index('ux_barcode_product', table_name='product_barcode')
    op.drop_index(op.f('ix_product_barcode_public_id'), table_name='product_barcode')
    op.drop_index('ix_barcode_code', table_name='product_barcode')
    op.drop_table('product_barcode')
    op.drop_index('ix_data_import_status', table_name='data_import')
    op.drop_index(op.f('ix_data_import_public_id'), table_name='data_import')
    op.drop_index('ix_data_import_created_by', table_name='data_import')
    op.drop_table('data_import')
    # ### end Alembic commands ###
