"""price observation staging + logical rollback columns

Revision ID: 8cda46a52c82
Revises: b0ac30649f65
Create Date: 2026-07-23 15:47:39.512645

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cda46a52c82'
down_revision: str | None = 'b0ac30649f65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_observation', sa.Column('staging_only', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('price_observation', sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('price_observation', sa.Column('rolled_back_by', sa.BigInteger(), nullable=True))
    op.add_column('price_observation', sa.Column('closed_by_run_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'price_observation', 'user', ['rolled_back_by'], ['id'])
    op.create_foreign_key(None, 'price_observation', 'crawl_run', ['closed_by_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_observation', type_='foreignkey')
    op.drop_constraint(None, 'price_observation', type_='foreignkey')
    op.drop_column('price_observation', 'closed_by_run_id')
    op.drop_column('price_observation', 'rolled_back_by')
    op.drop_column('price_observation', 'rolled_back_at')
    op.drop_column('price_observation', 'staging_only')
    # ### end Alembic commands ###
