"""Invariant test for the ingredient-consolidation Alembic migration.

Drives ``upgrade -> downgrade -> upgrade`` against a throwaway Postgres database created
just for the test (never the shared dev/prod DB). It seeds a fracture that mirrors the real
one — recipes pointing at accented/plural variant rows while the surviving slug carries the
active mapping — then asserts the structural invariants hold across the cycle:

* ``count(recipe_ingredient)`` is constant,
* ``sum(quantity)`` is constant,
* every recipe keeps at least one mandatory ingredient with a resolvable ``ingredient_id``,
* there are zero orphaned ingredient FKs,
* the fracture is consolidated on upgrade and exactly restored on downgrade,
* the migration is idempotent (a second upgrade reproduces the consolidated state).
"""

from __future__ import annotations

import os
import uuid
from collections.abc import Iterator
from decimal import Decimal
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config

from cestaplan_api.config import Settings, get_settings

_HEAD = "c7f4a1b9e2d3"
_BASE = "35d510ebc887"  # the revision this migration chains onto
_API_ROOT = Path(__file__).resolve().parents[2]

# Seed identity space (explicit ids; identity columns are GENERATED BY DEFAULT).
_ING = {
    "aceite_oliva": 1001,       # survivor — exact _SPECS key
    "aceite de oliva": 1002,    # variant of aceite_oliva
    "aceitunas": 1003,          # survivor — carries the active mapping
    "aceituna": 1004,           # variant of aceitunas
    "sal": 1005,                # lone canonical ingredient (never merged)
}
_PRODUCT_ID = 2001
_RECIPE_A = 3001
_RECIPE_B = 3002


@pytest.fixture()
def ephemeral_db() -> Iterator[sa.engine.url.URL]:
    base = sa.make_url(Settings().database_url)
    tmp_name = f"cestaplan_migtest_{uuid.uuid4().hex[:12]}"
    admin_engine = sa.create_engine(
        base.set(database="postgres"), isolation_level="AUTOCOMMIT"
    )
    with admin_engine.connect() as conn:
        conn.execute(sa.text(f'CREATE DATABASE "{tmp_name}"'))

    tmp_url = base.set(database=tmp_name)
    previous = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = tmp_url.render_as_string(hide_password=False)
    get_settings.cache_clear()
    try:
        yield tmp_url
    finally:
        if previous is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = previous
        get_settings.cache_clear()
        with admin_engine.connect() as conn:
            conn.execute(
                sa.text(
                    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                    "WHERE datname = :n AND pid <> pg_backend_pid()"
                ),
                {"n": tmp_name},
            )
            conn.execute(sa.text(f'DROP DATABASE IF EXISTS "{tmp_name}"'))
        admin_engine.dispose()


def _alembic_config() -> Config:
    cfg = Config(str(_API_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(_API_ROOT / "migrations"))
    return cfg


def _seed(engine: sa.engine.Engine) -> None:
    with engine.begin() as conn:
        for name, ingredient_id in _ING.items():
            conn.execute(
                sa.text(
                    "INSERT INTO ingredient (id, canonical_name, display_name, is_synthetic, "
                    "public_id) VALUES (:id, :name, :name, true, :pid)"
                ),
                {"id": ingredient_id, "name": name, "pid": uuid.uuid4()},
            )
        conn.execute(
            sa.text(
                "INSERT INTO product (id, name, is_synthetic, public_id) "
                "VALUES (:id, :name, true, :pid)"
            ),
            {"id": _PRODUCT_ID, "name": "Aceitunas Verdes 1kg", "pid": uuid.uuid4()},
        )
        # Active mapping targets the plural slug 'aceitunas' -> survivor priority (b).
        conn.execute(
            sa.text(
                "INSERT INTO ingredient_product_mapping "
                "(id, ingredient_id, product_id, is_active, public_id) "
                "VALUES (:id, :ing, :prod, true, :pid)"
            ),
            {"id": 4001, "ing": _ING["aceitunas"], "prod": _PRODUCT_ID, "pid": uuid.uuid4()},
        )
        for recipe_id in (_RECIPE_A, _RECIPE_B):
            conn.execute(
                sa.text(
                    "INSERT INTO recipe (id, origin, title, servings, is_public, is_synthetic, "
                    "public_id) VALUES (:id, 'seed', :title, 2, false, true, :pid)"
                ),
                {"id": recipe_id, "title": f"Recipe {recipe_id}", "pid": uuid.uuid4()},
            )
        # Recipes reference the VARIANT rows (the fracture) + the lone 'sal'.
        recipe_ings = [
            (5001, _RECIPE_A, _ING["aceite de oliva"], "aceite de oliva", "10.0000", "ml"),
            (5002, _RECIPE_A, _ING["sal"], "sal", "5.0000", "g"),
            (5003, _RECIPE_B, _ING["aceituna"], "aceituna", "20.0000", "g"),
            (5004, _RECIPE_B, _ING["sal"], "sal", "2.0000", "g"),
        ]
        for row_id, recipe_id, ingredient_id, name, qty, unit in recipe_ings:
            conn.execute(
                sa.text(
                    "INSERT INTO recipe_ingredient (id, recipe_id, ingredient_id, "
                    "canonical_name, quantity, unit, optional, public_id) "
                    "VALUES (:id, :rid, :ing, :name, :qty, :unit, false, :pid)"
                ),
                {
                    "id": row_id,
                    "rid": recipe_id,
                    "ing": ingredient_id,
                    "name": name,
                    "qty": qty,
                    "unit": unit,
                    "pid": uuid.uuid4(),
                },
            )


def _recipe_ingredient_snapshot(engine: sa.engine.Engine) -> dict[int, tuple[int, str]]:
    with engine.connect() as conn:
        rows = conn.execute(
            sa.text("SELECT id, ingredient_id, canonical_name FROM recipe_ingredient")
        ).all()
    return {row[0]: (row[1], row[2]) for row in rows}


def _quantity_sum(engine: sa.engine.Engine) -> Decimal:
    with engine.connect() as conn:
        return conn.execute(
            sa.text("SELECT COALESCE(SUM(quantity), 0) FROM recipe_ingredient")
        ).scalar_one()


def _orphan_fk_count(engine: sa.engine.Engine) -> int:
    with engine.connect() as conn:
        return conn.execute(
            sa.text(
                "SELECT COUNT(*) FROM recipe_ingredient ri "
                "LEFT JOIN ingredient i ON ri.ingredient_id = i.id WHERE i.id IS NULL"
            )
        ).scalar_one()


def _table_exists(engine: sa.engine.Engine, table: str) -> bool:
    with engine.connect() as conn:
        return conn.execute(
            sa.text("SELECT to_regclass(:t)"), {"t": f"public.{table}"}
        ).scalar_one() is not None


def _assert_consolidated(engine: sa.engine.Engine, count: int, quantity: Decimal) -> None:
    with engine.connect() as conn:
        # The two variant rows are gone; the three canonical rows remain.
        present = {
            row[0]
            for row in conn.execute(sa.text("SELECT id FROM ingredient")).all()
        }
        assert _ING["aceite de oliva"] not in present
        assert _ING["aceituna"] not in present
        assert {_ING["aceite_oliva"], _ING["aceitunas"], _ING["sal"]} <= present

        # No recipe row still points at a variant id.
        dangling = conn.execute(
            sa.text(
                "SELECT COUNT(*) FROM recipe_ingredient WHERE ingredient_id IN :ids"
            ).bindparams(sa.bindparam("ids", expanding=True)),
            {"ids": [_ING["aceite de oliva"], _ING["aceituna"]]},
        ).scalar_one()
        assert dangling == 0

        aliases = {
            row[0]: row[1]
            for row in conn.execute(
                sa.text("SELECT alias_text, ingredient_id FROM ingredient_alias")
            ).all()
        }
        assert aliases == {
            "aceite de oliva": _ING["aceite_oliva"],
            "aceituna": _ING["aceitunas"],
        }

        audits = {
            row[0]: row[1]
            for row in conn.execute(
                sa.text(
                    "SELECT old_ingredient_id, new_ingredient_id FROM ingredient_merge_audit"
                )
            ).all()
        }
        assert audits == {
            _ING["aceite de oliva"]: _ING["aceite_oliva"],
            _ING["aceituna"]: _ING["aceitunas"],
        }

        # Every recipe still has a mandatory ingredient with a resolvable FK.
        for recipe_id in (_RECIPE_A, _RECIPE_B):
            mandatory = conn.execute(
                sa.text(
                    "SELECT COUNT(*) FROM recipe_ingredient ri "
                    "JOIN ingredient i ON ri.ingredient_id = i.id "
                    "WHERE ri.recipe_id = :r AND ri.optional = false"
                ),
                {"r": recipe_id},
            ).scalar_one()
            assert mandatory >= 1

    # Aggregate invariants + integrity.
    assert len(_recipe_ingredient_snapshot(engine)) == count
    assert _quantity_sum(engine) == quantity
    assert _orphan_fk_count(engine) == 0


def test_migration_up_down_up_preserves_invariants(
    ephemeral_db: sa.engine.url.URL,
) -> None:
    cfg = _alembic_config()
    command.upgrade(cfg, _BASE)

    engine = sa.create_engine(ephemeral_db)
    try:
        _seed(engine)
        before = _recipe_ingredient_snapshot(engine)
        before_count = len(before)
        before_sum = _quantity_sum(engine)
        assert before_count == 4

        # --- upgrade: the fracture is consolidated ---
        command.upgrade(cfg, "head")
        _assert_consolidated(engine, before_count, before_sum)

        # --- downgrade: exact restoration + audit/alias tables dropped ---
        command.downgrade(cfg, _BASE)
        assert _recipe_ingredient_snapshot(engine) == before
        assert _quantity_sum(engine) == before_sum
        assert _orphan_fk_count(engine) == 0
        assert not _table_exists(engine, "ingredient_alias")
        assert not _table_exists(engine, "ingredient_merge_audit")

        # --- upgrade again: idempotent, reproduces the consolidated state ---
        command.upgrade(cfg, "head")
        _assert_consolidated(engine, before_count, before_sum)
    finally:
        engine.dispose()
